export type AsWrLookupEntry = {
  client: string;
  workRequest: string;
  taskNo: number;
  taskName: string;
  sdc: string;
  project: string;
};

export const AS_WR_LOOKUP: AsWrLookupEntry[] = [
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57712.0, taskName: "IJIS BAU SUPPORT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "FINES RECOVERY UNIT", workRequest: "FRU", taskNo: 58140.0, taskName: "FRU DEVELOPMENT WORK", sdc: "A68", project: "FRU" },
  { client: "FINES RECOVERY UNIT", workRequest: "FRU IMPORTS & AUTOMATION", taskNo: 58142.0, taskName: "DS-FRU-IJIS IMP & AUTOM", sdc: "A68", project: "FRU" },
  { client: "DIPL - DCS APPS", workRequest: "DLI DCS APPS SUPPORT TIME T&M", taskNo: 58143.0, taskName: "DLI REDFLEX IJIS INTEGRATION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57415.0, taskName: "LEGAWEB FAMILIARISATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 58146.0, taskName: "RDO FOR JCL & COBOL", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57154.0, taskName: "TMS - DATAZAP/CORRECTION", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - INFRA PLAN", workRequest: "DLI INSPECTION REGIME CHANGES", taskNo: 58145.0, taskName: "DLI INSPECTION REGIME APP DEV", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57486.0, taskName: "MOVERS NAB_ISSUES", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - INFRA PLAN", workRequest: "DLI INSPECTION REGIME CHANGES", taskNo: 58145.0, taskName: "DLI INSPECTION REGIME APP DEV", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DLA - IT MANAGEMENT", workRequest: "LA - NOTES DEV T & M", taskNo: 56605.0, taskName: "LA LOTUS NOTES 104312 T&M", sdc: "A10", project: "LA LOTUS NOTES" },
  { client: "DIPL - DCS APPS", workRequest: "DIS - NOTES DEV T & M", taskNo: 56607.0, taskName: "DIS LOTUS NOTES SUPPORT T&M", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "DCIS ASNEX", workRequest: "AIS NTGPAY PROJECT 681000764", taskNo: 58138.0, taskName: "AIS NTGPAY PROJECT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57142.0, taskName: "FLEET - DATAZAP/CORRECTION", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - INFRA PLAN", workRequest: "DLI INSPECTION REGIME CHANGES", taskNo: 58145.0, taskName: "DLI INSPECTION REGIME APP DEV", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57712.0, taskName: "IJIS BAU SUPPORT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "FINES RECOVERY UNIT", workRequest: "FRU", taskNo: 58140.0, taskName: "FRU DEVELOPMENT WORK", sdc: "A68", project: "FRU" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57320.0, taskName: "REPAIR MISHAPS", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57415.0, taskName: "LEGAWEB FAMILIARISATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57154.0, taskName: "TMS - DATAZAP/CORRECTION", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57486.0, taskName: "MOVERS NAB_ISSUES", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DLA - IT MANAGEMENT", workRequest: "LA - NOTES DEV T & M", taskNo: 56605.0, taskName: "LA LOTUS NOTES 104312 T&M", sdc: "A10", project: "LA LOTUS NOTES" },
  { client: "DIPL - DCS APPS", workRequest: "DIS - NOTES DEV T & M", taskNo: 56607.0, taskName: "DIS LOTUS NOTES SUPPORT T&M", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "DCIS ASNEX", workRequest: "AIS NTGPAY PROJECT 681000764", taskNo: 58138.0, taskName: "AIS NTGPAY PROJECT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57142.0, taskName: "FLEET - DATAZAP/CORRECTION", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57160.0, taskName: "TAXAD - DATAZAP/CORRECTION", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "TERRITORY REVENUE OF", workRequest: "REVCONNECT PROJECT 681000497", taskNo: 58020.0, taskName: "TAXAD-REVCONNECT REQTS", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57712.0, taskName: "IJIS BAU SUPPORT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58132.0, taskName: "ANALYSIS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57415.0, taskName: "LEGAWEB FAMILIARISATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57154.0, taskName: "TMS - DATAZAP/CORRECTION", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "HOUSING JULY", taskNo: 58139.0, taskName: "TMS WORK", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57142.0, taskName: "FLEET - DATAZAP/CORRECTION", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "HOUSING JULY", taskNo: 58139.0, taskName: "TMS WORK", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "DIS - NOTES DEV T & M", taskNo: 56607.0, taskName: "DIS LOTUS NOTES SUPPORT T&M", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "DCIS ASNEX", workRequest: "AIS NTGPAY PROJECT 681000764", taskNo: 58138.0, taskName: "AIS NTGPAY PROJECT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57142.0, taskName: "FLEET - DATAZAP/CORRECTION", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "TERRITORY REVENUE OF", workRequest: "REVCONNECT PROJECT 681000497", taskNo: 58020.0, taskName: "TAXAD-REVCONNECT REQTS", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "DCIS - DHCD - ITM", workRequest: "HOUSING JULY", taskNo: 58139.0, taskName: "TMS WORK", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "HOUSING JULY", taskNo: 58139.0, taskName: "TMS WORK", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57712.0, taskName: "IJIS BAU SUPPORT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58131.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58132.0, taskName: "ANALYSIS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57320.0, taskName: "REPAIR MISHAPS", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58131.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57157.0, taskName: "TAXAD - RELEASE MANAGEMENT", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57488.0, taskName: "TAXAD NAB_ISSUES", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57670.0, taskName: "ALDON LEGAWEB MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57154.0, taskName: "TMS - DATAZAP/CORRECTION", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57426.0, taskName: "ANALYSIS", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "HR - PAPMS", workRequest: "PAPMS APPLICATION BACKUP", taskNo: 58075.0, taskName: "PAPMS FAMILIARISATION", sdc: "A68", project: "BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DLA - IT MANAGEMENT", workRequest: "LA - NOTES DEV T & M", taskNo: 56605.0, taskName: "LA LOTUS NOTES 104312 T&M", sdc: "A10", project: "LA LOTUS NOTES" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57488.0, taskName: "TAXAD NAB_ISSUES", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57649.0, taskName: "LEGAWEB UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57649.0, taskName: "LEGAWEB UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57712.0, taskName: "IJIS BAU SUPPORT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58131.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58132.0, taskName: "ANALYSIS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58131.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57159.0, taskName: "TAXAD - ENHANCEMENT", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57415.0, taskName: "LEGAWEB FAMILIARISATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57154.0, taskName: "TMS - DATAZAP/CORRECTION", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 58092.0, taskName: "BIRT UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "HR - PAPMS", workRequest: "PAPMS APPLICATION BACKUP", taskNo: 58075.0, taskName: "PAPMS FAMILIARISATION", sdc: "A68", project: "BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "DIS - NOTES DEV T & M", taskNo: 56607.0, taskName: "DIS LOTUS NOTES SUPPORT T&M", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57157.0, taskName: "TAXAD - RELEASE MANAGEMENT", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57159.0, taskName: "TAXAD - ENHANCEMENT", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57160.0, taskName: "TAXAD - DATAZAP/CORRECTION", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57487.0, taskName: "IJIS NAB_ISSUES", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57488.0, taskName: "TAXAD NAB_ISSUES", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57139.0, taskName: "FLEET - RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57649.0, taskName: "LEGAWEB UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 58042.0, taskName: "SERVER UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57712.0, taskName: "IJIS BAU SUPPORT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS MOG CHANGES", taskNo: 58096.0, taskName: "ANALYSIS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS MOG CHANGES", taskNo: 58097.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58131.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "CRIME REDUCTION", taskNo: 58132.0, taskName: "ANALYSIS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57133.0, taskName: "IJIS - DATA ZAP / CORRECTION", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57134.0, taskName: "IJIS - ENHANCEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57135.0, taskName: "IJIS - REPORTS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57669.0, taskName: "ALDON EGL MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS MOG CHANGES", taskNo: 58097.0, taskName: "DEVELOPMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57157.0, taskName: "TAXAD - RELEASE MANAGEMENT", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57159.0, taskName: "TAXAD - ENHANCEMENT", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57415.0, taskName: "LEGAWEB FAMILIARISATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58107.0, taskName: "PROJECT MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57151.0, taskName: "TMS - RELEASE MANAGEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57153.0, taskName: "TMS - ENHANCEMENT", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57154.0, taskName: "TMS - DATAZAP/CORRECTION", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58110.0, taskName: "OTHER", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 58092.0, taskName: "BIRT UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58107.0, taskName: "PROJECT MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58114.0, taskName: "UAT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58115.0, taskName: "RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57137.0, taskName: "IJIS - RELEASE MANAGEMENT", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57145.0, taskName: "MOVERS - RELEASE MANAGEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57148.0, taskName: "MOVERS - DATAZAP/CORRECTION", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DLA - IT MANAGEMENT", workRequest: "LA - NOTES DEV T & M", taskNo: 56605.0, taskName: "LA LOTUS NOTES 104312 T&M", sdc: "A10", project: "LA LOTUS NOTES" },
  { client: "DIPL - DCS APPS", workRequest: "DIS - NOTES DEV T & M", taskNo: 56607.0, taskName: "DIS LOTUS NOTES SUPPORT T&M", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS ASNEX", workRequest: "ASNEX - AIS MF DEVELOPMENT", taskNo: 57771.0, taskName: "AIS - MF APPLICATION DEVELPMNT", sdc: "A68", project: "ASSET MANAGEMENT SYS" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "AGD ATT GEN JUS", workRequest: "IJIS - APPLN DEV - 79XCJA01D", taskNo: 57132.0, taskName: "IJIS - TECH ADVICE / INVESTIG", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57141.0, taskName: "FLEET - ENHANCEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57142.0, taskName: "FLEET - DATAZAP/CORRECTION", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "TAXAD - APPLICATION DEVLOPMENT", taskNo: 57161.0, taskName: "TAXAD - TECH ADV/INVESTIGATE", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57186.0, taskName: "STAFF TRAINING", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57205.0, taskName: "DCS MAINFRAME UPGRADES", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57147.0, taskName: "MOVERS - ENHANCEMENT", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57562.0, taskName: "TIMESHEET PREPARATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57110.0, taskName: "GENERAL ADMINISTRATION", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "NT FLEET - APPLICATION DVLPMNT", taskNo: 57143.0, taskName: "FLEET - TECH ADV/INVESTIGATE", sdc: "A62", project: "NT FLEET" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57149.0, taskName: "MOVERS - TECH ADV/INVESTIGATE", sdc: "A60", project: "DIPL - TRANSPORT DCI" },
  { client: "DCIS - DHCD - ITM", workRequest: "TMS - APPLICATION DVLPMNT", taskNo: 57155.0, taskName: "TMS - TECH ADV/INVESTIGATE", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57425.0, taskName: "LEGASUITE MAINTENANCE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57649.0, taskName: "LEGAWEB UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "ALDON MAINTENANCE", taskNo: 57702.0, taskName: "ALDON UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 58092.0, taskName: "BIRT UPGRADE", sdc: "A68", project: "NON-BILLABLE" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58115.0, taskName: "RELEASE MANAGEMENT", sdc: "A62", project: "NT FLEET" },
  { client: "AGD ATT GEN JUS", workRequest: "SERPRO TICKETS", taskNo: 58149.0, taskName: "SERPRO TICKETS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "PROJECT MANAGMENT", workRequest: "SERPRO ISSUES", taskNo: 58050.0, taskName: "DEVELOPMENT SERPRO", sdc: "A68", project: "IJIS MANAGEMENT A68" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58113.0, taskName: "SYSTEM TESTING FIX", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58112.0, taskName: "SYSTEM TESTING", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58108.0, taskName: "LEGAWEB FRONT END", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58113.0, taskName: "SYSTEM TESTING FIX", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS NT FLEET", workRequest: "FBS-691 MODERNISE AP", taskNo: 58109.0, taskName: "LEGAWEB BACKEND", sdc: "A62", project: "NT FLEET" },
  { client: "DCIS - DHCD - ITM", workRequest: "DC362619 - GEH BILLING PROCESS", taskNo: 57974.0, taskName: "ANALYSIS", sdc: "A68", project: "TERRITORY HOUSING" },
  { client: "NON-BILLABLE", workRequest: "APPLICATION SERVICES", taskNo: 57815.0, taskName: "EGL DEVOPS", sdc: "A68", project: "NON-BILLABLE" },
  { client: "IJIS MANAGEMENT", workRequest: "DC333282 CONV COBOL TO BIRT", taskNo: 58004.0, taskName: "CONV COBOL TO BIRT", sdc: "A68", project: "NON-BILLABLE" },
  { client: "TERRITORY REVENUE OF", workRequest: "REVCONNECT PROJECT 681000497", taskNo: 57959.0, taskName: "DATA EXTRACTION", sdc: "A68", project: "DCDD EPS TAXAD" },
  { client: "DIPL - DCS APPS", workRequest: "MOVERS - APPLICATION DVLPMNT", taskNo: 57589.0, taskName: "REPAIR MISHAPS", sdc: "A60", project: "NON-BILLABLE" },
  { client: "PROJECT MANAGMENT", workRequest: "SERPRO ISSUES", taskNo: 58047.0, taskName: "ANALYSIS", sdc: "A68", project: "IJIS MANAGEMENT A68" },
];
