export type ContractorAllocation = {
  pramms: string;
  name: string;
  workgroup: string;
  costCentre: string;
  hourlyRateExGst: number;
  escalationPct: number;
  allocations: Record<string, number>;
};

export const CONTRACTOR_ALLOCATIONS: ContractorAllocation[] = [
  { pramms: "Widianto, Gregorius", name: "Gregorius Widianto", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 120.0, escalationPct: 0.04, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Wise, Michael", name: "Michael Wise", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 121.9, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Thompson, Anthony", name: "Anthony Thompson", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 103.64, escalationPct: 0.0, allocations: { "BASE": 1.0 } },
  { pramms: "Dewson, Heath", name: "Heath Dewson", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 109.68, escalationPct: 0.0, allocations: { "BASE": 1.0 } },
  { pramms: "Fleming, Simon", name: "Simon Fleming", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 151.25, escalationPct: 0.0, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Austin, Nick", name: "Nick Austin", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 124.0, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Lowe, Roger", name: "Roger Lowe", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 122.32, escalationPct: 0.0, allocations: { "BASE": 1.0 } },
  { pramms: "Govender, Malcolm", name: "Malcolm Govender", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 90.5, escalationPct: 0.15, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Fischer, Andre", name: "Andre Fischer", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 132.0, escalationPct: 0.0, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Parian, Oscar", name: "Oscar Parian", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 101.34, escalationPct: 0.0, allocations: { "DB2": 1.0 } },
  { pramms: "Lontoc, Angelito", name: "Angelito Lontoc", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 110.0, escalationPct: 0.0, allocations: { "BASE": 1.0 } },
  { pramms: "McCarthy, Paul", name: "Paul McCarthy", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 129.51, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Marbella, Julius", name: "Julius Marbella", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 107.96, escalationPct: 0.0, allocations: { "EGL": 0.5, "BASE": 0.5 } },
  { pramms: "Marshall, Campbell", name: "Campbell Marshall", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 142.49, escalationPct: 0.0, allocations: { "BASE": 1.0 } },
  { pramms: "Heydarpour, Amir", name: "Amir Heydarpour", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 110.91, escalationPct: 0.0, allocations: { "DB2": 1.0 } },
  { pramms: "Bogachev, Alex", name: "Alex Bogachev", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 124.09, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Brewer, Kim", name: "Kim Brewer", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 115.87, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Gurran, Matthew", name: "Matthew Gurran", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 113.77, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Bhattacharya, Arijit", name: "Arijit Bhattacharya", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 119.29, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Chaudhary, Jagbir", name: "Jagbir Chaudhary", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 113.77, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Barretto, Max", name: "Max Barretto", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 103.0, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Simpkins, Gilbert", name: "Gilbert Simpkins", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 138.37, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Ravi, Praveen", name: "Praveen Ravi", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 108.15, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Barretto, Chai", name: "Chai Barretto", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 114.33, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Williamson, Mark", name: "Mark Williamson", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 120.82, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Fung, Michael", name: "Michael Fung", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 120.95, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Ngai, Jayrick", name: "Jayrick Ngai", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 113.3, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Lingamaneni, Harita", name: "Harita Lingamaneni", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 113.3, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Dodge, Kevin", name: "Kevin Dodge", workgroup: "Application Services", costCentre: "661081", hourlyRateExGst: 120.95, escalationPct: 0.038, allocations: { "Application Services": 1.0 } },
  { pramms: "Sidhu, Puneet", name: "Puneet Sidhu", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 72.0, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Yorke-Barber, John", name: "John Yorke-Barber", workgroup: "Mainframe", costCentre: "661011", hourlyRateExGst: 84.55, escalationPct: 0.0, allocations: { "BASE": 1.0 } },
  { pramms: "Ghodela, Yogi", name: "Yogesh Ghodela", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 118.18, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
  { pramms: "Bhattarai, Samarpan", name: "Samarpan Bhattarai", workgroup: "Midrange", costCentre: "661021", hourlyRateExGst: 115.0, escalationPct: 0.03, allocations: { "mySQL": 0.01, "Application Hosting": 0.05, "Oracle Database Hosting": 0.05, "SQL Database Hosting": 0.09, "Windows OS": 0.16, "RedHat OS": 0.01, "Website Hosting Services": 0.03, "Sharepoint": 0.03, "VMWare": 0.36, "Domino / Lotus Notes": 0.09, "App Management": 0.02, "Disk Fixed File": 0.1 } },
];
