export type IbisLookupEntry = {
  agencyId: string;
  billingOrg: string;
  ibisCode: string;
  customerName: string;
  agencySdc: string;
  externalSdc: string;
  sdc: string;
};

export const IBIS_LOOKUP: IbisLookupEntry[] = [
  { agencyId: "10", billingOrg: "66", ibisCode: "10IBS661001", customerName: "Legislative Assembly", agencySdc: "A10", externalSdc: " ", sdc: "A10" },
  { agencyId: "11", billingOrg: "66", ibisCode: "11IBS661001", customerName: "Chief Minister", agencySdc: "A11", externalSdc: "", sdc: "A11" },
  { agencyId: "12", billingOrg: "66", ibisCode: "12IBS661001", customerName: "NT Electoral Commission", agencySdc: "A12", externalSdc: "", sdc: "A12" },
  { agencyId: "14", billingOrg: "66", ibisCode: "14IBS661001", customerName: "AGO", agencySdc: "A14", externalSdc: "", sdc: "A14" },
  { agencyId: "15", billingOrg: "66", ibisCode: "15IBS661001", customerName: "Ombudsman", agencySdc: "A15", externalSdc: "", sdc: "A15" },
  { agencyId: "16", billingOrg: "66", ibisCode: "16IBS661001", customerName: "PFES", agencySdc: "A16", externalSdc: "", sdc: "A16" },
  { agencyId: "17", billingOrg: "66", ibisCode: "17IBS661001", customerName: "Independent Commissioner Against Corruption ", agencySdc: "A17", externalSdc: "", sdc: "A17" },
  { agencyId: "19", billingOrg: "66", ibisCode: "19IBS661001", customerName: "NT Home Ownership", agencySdc: "A19", externalSdc: "", sdc: "A19" },
  { agencyId: "21", billingOrg: "66", ibisCode: "21IBS661001", customerName: "Treasury\\Treasury, Corporation", agencySdc: "A21", externalSdc: "", sdc: "A21" },
  { agencyId: "23", billingOrg: "66", ibisCode: "23IBS661001", customerName: "Land Dev. Corp.", agencySdc: "A23", externalSdc: "", sdc: "A23" },
  { agencyId: "27", billingOrg: "66", ibisCode: "27IBS661001", customerName: "Darwin Waterfront Corporation", agencySdc: "A27", externalSdc: "", sdc: "A27" },
  { agencyId: "32", billingOrg: "66", ibisCode: "32IBS661001", customerName: "Aboriginal Areas PA", agencySdc: "A32", externalSdc: "", sdc: "A32" },
  { agencyId: "35", billingOrg: "66", ibisCode: "35IBS661001", customerName: "DOE\\DOE - Corporate Communication", agencySdc: "A35", externalSdc: "", sdc: "A35" },
  { agencyId: "36", billingOrg: "66", ibisCode: "36IBS661001", customerName: "Batchelor Institute of Indigenous Tertiary Education", agencySdc: "A36", externalSdc: "", sdc: "A36" },
  { agencyId: "40", billingOrg: "66", ibisCode: "40IBS661001", customerName: "DEPW", agencySdc: "A40", externalSdc: "", sdc: "A40" },
  { agencyId: "50", billingOrg: "66", ibisCode: "50IBS661001", customerName: "DEPT OF ENVIRONMENT, PARKS & WATER SECURITY", agencySdc: "A50", externalSdc: "", sdc: "A50" },
  { agencyId: "51", billingOrg: "66", ibisCode: "51IBS661003", customerName: "DEPARTMENT OF TERRITORY FAMILIES, HOUSING AND COMM", agencySdc: "A51", externalSdc: "", sdc: "A51" },
  { agencyId: "53", billingOrg: "66", ibisCode: "53IBS661002", customerName: "LEGAL AID COMMISSION. NORTHERN TERRITORY* IT MGT", agencySdc: "A53", externalSdc: "", sdc: "A53" },
  { agencyId: "60", billingOrg: "66", ibisCode: "60IBS661002", customerName: "DIPL - INFRASTRUCTURE, PLANNING AND LOGISTICS", agencySdc: "A60", externalSdc: "", sdc: "A60" },
  { agencyId: "60", billingOrg: "66", ibisCode: "60IBS661005", customerName: "DIPL - MVR BIOMETRICS PROJECT MANAGER", agencySdc: "A60", externalSdc: "", sdc: "A60" },
  { agencyId: "60", billingOrg: "66", ibisCode: "60IBS661006", customerName: "DIPL - TRAFFIC SECTION", agencySdc: "A60", externalSdc: "", sdc: "A66" },
  { agencyId: "62", billingOrg: "66", ibisCode: "62IBS661001", customerName: "DCDD\\DCDD * NT Fleet", agencySdc: "A62", externalSdc: "", sdc: "A62" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661001", customerName: "DCDD\\CCSRP", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661002", customerName: "DCDD\\ APPLICATION DEVELOPMENT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661003", customerName: "DCDD\\ EPASS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661004", customerName: "DCDD\\ ALLOY", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661006", customerName: "DCDD\\ CIS NTG RECORD SYSTEMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661007", customerName: "DCDD\\ CIS GAS SUPPORT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661010", customerName: "DCDD\\ ASNEX", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661012", customerName: "DCDD\\ CIS EIMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661013", customerName: "DCDD\\ EXECUTIVE SUPPORT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661014", customerName: "DCDD\\ CIS ECMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661017", customerName: "DCDD\\ CIS ICT SERVICES", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661020", customerName: "DCDD\\ CIS PROGEN", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661021", customerName: "DCDD\\ DCDD DATA SERVICES DW CORPORATE", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661022", customerName: "DCDD\\ CIS TRIPS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661023", customerName: "DCDD\\ TRAINING AND EMPLOYMENT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661024", customerName: "DCDD\\ CIS TAXATION SERVICES", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661026", customerName: "DCDD\\ CIS FEENIX", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661027", customerName: "DCDD\\ CIS PROJECT MANAGEMENT OFFICE", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661030", customerName: "DCDD\\ SMALL SYSTEMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661031", customerName: "DCDD\\ CIS DIGITAL COMMUNICATIONS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661034", customerName: "DCDD\\ CIS CORP SYS GRANTS NT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661035", customerName: "DCDD\\ CIS SERPRO", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661036", customerName: "DCDD\\ CIS PROCUREMENT SYSTEMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661037", customerName: "DCDD\\ EPS -CMSA", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661039", customerName: "DCDD\\ CORPORATE SYSTEMS HR SYSTEMS PAPMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661040", customerName: "DCDD\\ CORPORATE SYSTEMS HR SYSTEMS PIPS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661041", customerName: "DCDD\\ CORPORATE SYSTEMS HR SYSTEMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661044", customerName: "DCDD\\ DOE ECS DIGITAL", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661046", customerName: "DCDD\\ DOH PORTFOLIO SERVICES", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661048", customerName: "DCDD\\ DOH TECH SERVICES (TELEHEALTH)", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661049", customerName: "DCDD\\ DCDD DATA SERVICES DW HEALTH", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661050", customerName: "DCDD\\ DHCD ITM", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661051", customerName: "DCDD\\ DTSC ECS DIGITAL BUSINESS SYSTEMS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661053", customerName: "DCDD\\ DTSC ECS WEB", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661054", customerName: "DCDD\\ DTSC ECS DIGITAL", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661056", customerName: "DCDD\\ AGD ITM", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661062", customerName: "DCDD\\ TF IT MANAGEMENT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661063", customerName: "DCDD\\ DTBI BUSINESS SYSTEMS AND INFORMATION SERVIC", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661065", customerName: "DCDD\\ DATA STRATEGY", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661066", customerName: "DCDD\\ EPSIDM", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661069", customerName: "DCDD\\ DIGITAL STRATEGY", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661071", customerName: "DCDD\\ DCDD DTF ECS DIGITAL (APEX)", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661072", customerName: "DCDD\\ DCDD DTF ECS DIGITAL (DW)", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661073", customerName: "DCDD\\ DCDD DTF ECS DIGITAL (INTRA)", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661074", customerName: "DCDD\\ DCDD DTF ECS DIGITAL (SUPER)", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661077", customerName: "DCDD NDIS ENTERPRISE PROJECT SERVICES", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661078", customerName: "DCDD VERITAS PROJECT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661079", customerName: "DCDD SAGE PROJECT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661080", customerName: "DCDD EPS - RED TAPE", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661081", customerName: "DCDD AGS - ELEARNING", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661082", customerName: "DCDD COVID-19 DOMESTIC", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661083", customerName: "DCDD \\ DCDD * EPS - LDS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661084", customerName: "DCDD ABS4 AD-HOC REQUESTS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661085", customerName: "DCDD DATA SERVICES - ONENTG BI", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661086", customerName: "ENTERPRISE PROJECT SERVICES (TERRITORY PASS APP)", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661087", customerName: "ENTERPRISE PROJECT SERVICES/TRO", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661088", customerName: "DCDD DATA SERVICES - ONENTG ERI", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661089", customerName: "ABS 1 - BASFM + VEEMA", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661090", customerName: "DCDD DATA SERVICES - WOG WORKFORCE REPORTING", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661091", customerName: "DCDD WORKFORCE DEVELOPMENT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661092", customerName: "DCDD \u2013 EPS - TRACER PROJECT", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661093", customerName: "DCDD DIGITAL SOLUTIONS", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661094", customerName: "CMSA MDM", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661095", customerName: "DCDD DATA SERVICES - TFHC DATA WAREHOUSE", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661096", customerName: "DCDD\\DENODO", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661097", customerName: "DCDD AGS OPERATIONS CENTRE", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661098", customerName: "DCDD DATA SERVICES - POWER BI", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661099", customerName: "BANKING SERVICES", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661100", customerName: "DCDD DATA SERVICES - TABLEAU TEST", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "68", billingOrg: "66", ibisCode: "68IBS661101", customerName: "DCDD WHOLE AGENCY", agencySdc: "A68", externalSdc: "", sdc: "A68" },
  { agencyId: "70", billingOrg: "66", ibisCode: "70IBS661001", customerName: "DOH", agencySdc: "A70", externalSdc: "", sdc: "A70" },
  { agencyId: "79", billingOrg: "66", ibisCode: "79IBS661001", customerName: "AGD\\AGD * Correctional Services", agencySdc: "A79", externalSdc: "", sdc: "A79" },
  { agencyId: "79", billingOrg: "66", ibisCode: "79IBS661003", customerName: "AGD\\AGD * Darwin Correctional Facility Overheads", agencySdc: "A79", externalSdc: "", sdc: "A79" },
  { agencyId: "84", billingOrg: "66", ibisCode: "84IBS661002", customerName: "Territory Wildlife Park", agencySdc: "A84", externalSdc: "", sdc: "A84" },
  { agencyId: "91", billingOrg: "66", ibisCode: "91IBS661002", customerName: "DITT\\DITT * INDUSTRY, TOURISM AND TRADE", agencySdc: "A91", externalSdc: "", sdc: "A91" },
  { agencyId: "92", billingOrg: "66", ibisCode: "92IBS661002", customerName: "DITT\\DITT * BUSINESS & WORKFORCE", agencySdc: "A92", externalSdc: "", sdc: "A92" },
  { agencyId: "92", billingOrg: "66", ibisCode: "92IBS661003", customerName: "DITT\\DITT * Corporate Communications", agencySdc: "A92", externalSdc: "", sdc: "A92" },
  { agencyId: "92", billingOrg: "66", ibisCode: "92IBS661005", customerName: "DITT\\DITT * MIGRATION NT", agencySdc: "A92", externalSdc: "", sdc: "A92" },
  { agencyId: "92", billingOrg: "66", ibisCode: "92IBS661006", customerName: "DITT\\DITT * TERRITORY BUSINESS CENTRE", agencySdc: "A92", externalSdc: "", sdc: "A92" },
  { agencyId: "66", billingOrg: "BS", ibisCode: "DCISDBS500", customerName: "DCDD\\DCDD * DCS Enterprise Storage", agencySdc: "A66", externalSdc: "", sdc: "A66" },
  { agencyId: "66", billingOrg: "BS", ibisCode: "DCISDBS501", customerName: "DCDD\\DCDD * DCS Data Centre Operations", agencySdc: "A66", externalSdc: "", sdc: "A66" },
  { agencyId: "66", billingOrg: "BS", ibisCode: "DCISDBS504", customerName: "DCDD\\DCDD * DCS Midrange Services", agencySdc: "A66", externalSdc: "", sdc: "A66" },
  { agencyId: "66", billingOrg: "BS", ibisCode: "DCISMBS504", customerName: "DCDD\\DCDD * DCS Mainframe Services", agencySdc: "A66", externalSdc: "", sdc: "A66" },
  { agencyId: "66", billingOrg: "BS", ibisCode: "DCISWBS500", customerName: "DCDD\\DCDD * DCS Whole of Government", agencySdc: "A66", externalSdc: "", sdc: "A66" },
  { agencyId: "XX", billingOrg: "66", ibisCode: "XXIBS661004", customerName: "NT BUILD", agencySdc: "AXX", externalSdc: "A26", sdc: "A26" },
  { agencyId: "XX", billingOrg: "66", ibisCode: "XXIBS661006", customerName: "CouncilBiz", agencySdc: "AXX", externalSdc: "911", sdc: "911" },
  { agencyId: "XX", billingOrg: "66", ibisCode: "XXIBS661007", customerName: "Territory Generation", agencySdc: "AXX", externalSdc: "A43", sdc: "A43" },
  { agencyId: "XX", billingOrg: "66", ibisCode: "XXIBS661008", customerName: "PWC", agencySdc: "AXX", externalSdc: "A46", sdc: "A46" },
  { agencyId: "XX", billingOrg: "66", ibisCode: "XXIBS661016", customerName: "Jacana Energy", agencySdc: "AXX", externalSdc: "A42", sdc: "A42" },
  { agencyId: "XX", billingOrg: "66", ibisCode: "XXIBS661019", customerName: "AARNET", agencySdc: "AXX", externalSdc: "911", sdc: "911" },
];
