export type StdClassEntry = {
  code: string;
  description: string;
};

export const STD_CLASS: StdClassEntry[] = [
  { code: "122111", description: "CURRENT GRANTS-COMMONWEALTH OWN PURPOSE" },
  { code: "122211", description: "CURRENT GRANTS - SPECIFIC PURP" },
  { code: "122311", description: "OTHER GRANTS - AGENCY ARRANGE" },
  { code: "122411", description: "NON CAPITAL CONTRIBUTIONS" },
  { code: "123111", description: "CAPITAL GRANTS-COMMONWEALTH OWN PURPOSE" },
  { code: "123211", description: "CAPITAL GRANTS - SPECIFIC PURP" },
  { code: "123311", description: "CAPITAL GRANTS-AGENCY ARRANGEMENTS" },
  { code: "131111", description: "GOODS AND SERVICES INCOME" },
  { code: "131112", description: "SERVER TAPE MANAGEMENT" },
  { code: "131113", description: "USAGE BASED MAINFRAME CPU" },
  { code: "131114", description: "USAGE BASED MAINFRAME DISK" },
  { code: "131115", description: "FIXED MAINFRAME DISK, CPU, PRINT & TAPE" },
  { code: "131116", description: "USAGE BASED MAINFRAME PRINTING" },
  { code: "131117", description: "USAGE BASED MAINFRAME TAPE" },
  { code: "131118", description: "ENTERPRISE  BACKUP" },
  { code: "131119", description: "MPR" },
  { code: "131121", description: "SOFTWARE CHARGES" },
  { code: "131122", description: "IT PROCUREMENT CHARGES - HARDWARE" },
  { code: "131123", description: "IT PROCUREMENT CHARGES - SOFTWARE" },
  { code: "131124", description: "WAN NETWORK CONNECTION CHARGES" },
  { code: "131125", description: "SLA CLEARING" },
  { code: "131211", description: "FIXED MF APPLICATION SOFTWARE SUPPORT" },
  { code: "131212", description: "FIXED MAINFRAME DISK, CPU, PRINT AND TAPE" },
  { code: "131213", description: "MAINFRAME SNA CONNECTIONS" },
  { code: "131214", description: "USAGE BASED MAINFRAME CPU" },
  { code: "131215", description: "USAGE BASED MAINFRAME DISK" },
  { code: "131216", description: "USAGE BASED MAINFRAME PRINT" },
  { code: "131217", description: "USAGE BASED MAINFRAME TAPE" },
  { code: "131218", description: "TAPE STORAGE" },
  { code: "131219", description: "WAN SERVER CONNECTION CHAN BUILDING" },
  { code: "131221", description: "LIST SERVER HOSTING" },
  { code: "131222", description: "LOTUS NOTES DATABASE HOSTING" },
  { code: "131223", description: "APPLICATION HOSTING" },
  { code: "131224", description: "DATABASE SUPPORT" },
  { code: "131225", description: "OPERATING SYSTEM SUPPORT" },
  { code: "131226", description: "OUTPOST STAFF" },
  { code: "131227", description: "APP STORAGE FIXED" },
  { code: "131228", description: "SAN STORAGE" },
  { code: "131229", description: "REMOTE BACKUP LICENCES" },
  { code: "131231", description: "WOG LICENCES" },
  { code: "131232", description: "LOTUS NOTES LICENCES" },
  { code: "131233", description: "EPASS MONTHLY CHARGE" },
  { code: "131234", description: "EPASS SOFTWARE & MAINTENANCE" },
  { code: "131311", description: "INT REVENUE ELIMINATION" },
  { code: "131921", description: "APPRENTICE/TRAINEE CONTRIBUTIONS" },
  { code: "131988", description: "UNAPPLIED AR REVENUE" },
  { code: "132111", description: "OUTPUT INCOME" },
  { code: "133111", description: "COMM/GOVT SERVICE OBLIGATIONS" },
  { code: "134111", description: "FEES FROM REGULATORY SERVICES" },
  { code: "141111", description: "INTEREST INCOME" },
  { code: "145111", description: "GAIN/LOSS-FOREIGN EXCHANGE TRANSLATIONS" },
  { code: "146111", description: "LEASE INTEREST INCOME" },
  { code: "152111", description: "LAND RENT" },
  { code: "161111", description: "FINES" },
  { code: "162111", description: "CENTRAL HOLDING AUTHORITY ON-COSTS" },
  { code: "164111", description: "DBE GOODS & SRVC REC FOC" },
  { code: "164211", description: "AGENCY GOODS & SEVC REC FOC" },
  { code: "165111", description: "CAPITAL CONTRIBUTIONS" },
  { code: "165121", description: "R & M CONTRIBUTIONS" },
  { code: "166111", description: "FROM SELF INSURANCE CLAIMS" },
  { code: "166211", description: "UNCLAIMED MONEY" },
  { code: "166311", description: "INFORMATION ACT REVENUE" },
  { code: "166911", description: "PRIOR YEAR REFUND" },
  { code: "166912", description: "OTHER MISCELLANEOUS INCOME" },
  { code: "171111", description: "SALE OF MINOR ASSETS" },
  { code: "172111", description: "GAIN/LOSS LAND" },
  { code: "172211", description: "GAIN/LOSS BUILDINGS" },
  { code: "172311", description: "GAIN/LOSS INFRASTR ASSETS" },
  { code: "172411", description: "GAIN/LOSS PLANT AND EQUIPMENT" },
  { code: "172511", description: "GAIN/LOSS COMPUTER SOFTWARE" },
  { code: "172611", description: "GAIN/LOSS COMPUTER HARDWARE" },
  { code: "172711", description: "GAIN/LOSS TRANSPORT EQUIP" },
  { code: "172811", description: "GAIN/LOSS CULTURAL ASSETS" },
  { code: "173111", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - LAND" },
  { code: "173211", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - BUILDINGS" },
  { code: "173311", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - INFRASTRUCTURE ASSETS" },
  { code: "173411", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - PLANT AND EQUIPMENT" },
  { code: "173511", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - COMPUTER SOFTWARE" },
  { code: "173611", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - COMPUTER HARDWARE" },
  { code: "173711", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - TRANSPORT EQUIPMENT" },
  { code: "173811", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - CULTURAL ASSETS" },
  { code: "173911", description: "ASSETS ACQUIRED FOR NIL CONSIDERATION - INTANGIBLE ASSETS" },
  { code: "174111", description: "GAIN/LOSS EQUITY INVESTMENTS" },
  { code: "175111", description: "REVALUATION INCREMENT" },
  { code: "211111", description: "SALARIES - PIPS POSTING LEVEL" },
  { code: "211211", description: "RECREATION LEAVE - PIPS POSTING LEVEL" },
  { code: "211311", description: "LONG SERVICE LEAVE - PIPS POSTING LEVEL" },
  { code: "211411", description: "RECREATION LEAVE LOADING - PIPS POSTING LEVEL" },
  { code: "211511", description: "OTHER LEAVE - PIPS" },
  { code: "212111", description: "HIGHER DUTIES ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212211", description: "MEAL ALLOWANCE" },
  { code: "212311", description: "NT ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212321", description: "OTHER NT ALLOWANCE" },
  { code: "212411", description: "PERISHABLE FREIGHT ALLOWANCE" },
  { code: "212412", description: "REPORTABLE FREIGHT FBT" },
  { code: "212422", description: "NON-REPORTABLE FREIGHT FBT" },
  { code: "212511", description: "REMOTE LOCALITY ACCOM (FBT)" },
  { code: "212521", description: "REMOTE ACCOM (NON-FBT)" },
  { code: "212531", description: "FARES OUT OF ISOLATED LOCATION (FOIL) ALLOWANCE" },
  { code: "212541", description: "REMOTE LOCALITY ALLOWANCE" },
  { code: "212611", description: "ACCOMMODATION ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212612", description: "CONSOLIDATED ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212613", description: "PENALTY PAYMENTS - PIPS POSTING LEVEL" },
  { code: "212614", description: "FREIGHT ON HOUSEHOLD GOODS ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212615", description: "RESPONSIBILITY ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212616", description: "SHIFT ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212617", description: "ELECTORAL ALLOWANCE - PIPS POSTING LEVEL" },
  { code: "212618", description: "ALLOWANCE FOR USE OF EMPLOYEE'S VEHICLE" },
  { code: "212619", description: "OTHER PIPS ALLOWANCES - PIPS POSTING LEVEL" },
  { code: "212911", description: "LSL ALLOWANCES RECOVERED - PIPS" },
  { code: "213111", description: "OVERTIME - PIPS POSTING LEVEL" },
  { code: "214111", description: "AIRFARE FROM DARWIN" },
  { code: "214211", description: "AIRFARE FROM OTHER THAN DARWIN" },
  { code: "214311", description: "REMOTE LOCALITY FARES" },
  { code: "214411", description: "RECREATION LEAVE FARES PAID IN CASH  - PIPS POSTING LEVEL" },
  { code: "215111", description: "SALARY SACRIFICE - VOLUNTARY SUPERANNUATION CONTRIBUTIONS - PIPS POSTING LEVEL" },
  { code: "215211", description: "SALARY SACRIFICE SUBJECT TO FBT - PIPS POSTING LEVEL" },
  { code: "215212", description: "FBT EXPENSE ON SALARY SACRIFICE - PIPS POSTING LEVEL" },
  { code: "215251", description: "SALARY SACRIFICE NOT SUBJECT TO FBT - PIPS POSTING " },
  { code: "215811", description: "LSL BENEFITS RECOVERED - PIPS" },
  { code: "215911", description: "BENEFITS - OTHER" },
  { code: "216111", description: "REDUNDANCY AND RELATED PAYMENTS - PIPS POSTING " },
  { code: "217111", description: "EXECUTIVE CONTRACT  BENEFITS" },
  { code: "218111", description: "LABOUR HIRE COSTS" },
  { code: "219111", description: "PERSONNEL COST ALLOCATION" },
  { code: "219112", description: "SHARED PERSONAL ALLOCATION" },
  { code: "219113", description: "SERVICE DESK ALLOCATION" },
  { code: "231111", description: "PAYROLL TAX" },
  { code: "231119", description: "PAYROLL TAX ON-COSTS" },
  { code: "241111", description: "FRINGE BENEFITS TAX EXPENSE" },
  { code: "242111", description: "FBT RECOVERY" },
  { code: "243111", description: "FRINGE BENEFITS TAX PENALTIES" },
  { code: "251111", description: "EMPLOYER COMPULSORY INTERNAL CONTRIBUTIONS - PIPS POSTING LEVEL" },
  { code: "251112", description: "GBD ADDITIONAL SUPERANNUATION CONTRIBUTIONS" },
  { code: "251211", description: "EMPLOYER COMPULSORY EXTERNAL CONTRIBUTIONS - PIPS POSTING LEVEL" },
  { code: "252111", description: "ECO EMPLOYER COMPULSORY INTERNAL SUPERANNUATION CONTRIBUTIONS - PIPS POSTING LEVEL" },
  { code: "252211", description: "ECO EMPLOYER COMPULSORY EXTERNAL SUPERANNUATION CONTRIBUTIONS - PIPS POSTING LEVEL" },
  { code: "253311", description: "UNFUNDED SUPERANNUATION REVALUATION" },
  { code: "261111", description: "WEEKLY BENEFITS - PIPS POSTING LEVEL" },
  { code: "262111", description: "COMMON LAW PAYMENTS" },
  { code: "263111", description: "DEATH BENEFITS" },
  { code: "263112", description: "HOPKINS DEED" },
  { code: "263211", description: "PERMANENT IMPAIRMENT" },
  { code: "264111", description: "HOSPITALISATION AND TREATMENT" },
  { code: "265111", description: "LEGAL FEES" },
  { code: "266111", description: "MEDICAL EXPENSES" },
  { code: "267111", description: "REHABILITATION EXPENSES" },
  { code: "268111", description: "TIO ADMINISTRATION FEES" },
  { code: "269111", description: "ASSESSORS / SURVEILLANCE EXP" },
  { code: "311111", description: "NT R & M PROGRAM" },
  { code: "312111", description: "R & M - EXTERNALLY FUNDED" },
  { code: "313111", description: "R & M MANAGEMENT EXPENSES" },
  { code: "314111", description: "R & M -MINOR NEW WORKS NON CASH" },
  { code: "321111", description: "CLEANING OF PREMISES" },
  { code: "321112", description: "MINOR REPAIRS & MAINTENANCE" },
  { code: "321113", description: "PARKING & SECURITY" },
  { code: "322111", description: "RENT/LEASE OF PREMISES" },
  { code: "322211", description: "PROPERTY MANAGEMENT OVERHEAD" },
  { code: "323111", description: "POWER" },
  { code: "323112", description: "AFTER HOURS AIRCON" },
  { code: "323113", description: "POWER OTHER" },
  { code: "324111", description: "WATER AND SEWERAGE" },
  { code: "325111", description: "LAND RENT EXPENSE" },
  { code: "326111", description: "PROPERTY MANAGEMENT OVERHEAD" },
  { code: "329111", description: "PROPERTY MANAGEMENT - LEASE CONTRA" },
  { code: "331111", description: "INTRA TERRITORY ACCOMMODATION" },
  { code: "331211", description: "INTERSTATE ACCOMMODATION" },
  { code: "331311", description: "OVERSEAS ACCOMMODATION" },
  { code: "332111", description: "ADVERTISING" },
  { code: "333111", description: "DCIS CORPORATE SUPPORT CHARGES" },
  { code: "333112", description: "DCIS SLA EXECUTIVE CORP SUPPORT" },
  { code: "333113", description: "DCIS SLA Finance Support" },
  { code: "333114", description: "DCIS SLA Procurement Support" },
  { code: "333119", description: "OTHER AGENCY SERVICE ARRANGEMENTS" },
  { code: "335111", description: "AUDIT FEES" },
  { code: "336111", description: "MERCHANT FEES" },
  { code: "336112", description: "MONEY DIRECT PROCESSING FEE" },
  { code: "336113", description: "VOICE/TELEPHONE TRANSACTION FEE" },
  { code: "336114", description: "MERCHANT FACILITIES CHARGES & FEES" },
  { code: "336115", description: "BPAY" },
  { code: "336116", description: "WEB/ONLINE TRANSACTION FEES" },
  { code: "336117", description: "MERCHANT SERVICES - OTHER" },
  { code: "336211", description: "NAB PAYMENTS" },
  { code: "336212", description: "WIBS FEES" },
  { code: "336213", description: "ACCOUNT TRANSACTIONS - OTHER" },
  { code: "336311", description: "CREDIT CARD SURCHARGE" },
  { code: "336315", description: "CARDHOLDER ANNUAL FEES" },
  { code: "336316", description: "CREDIT CARD CHARGES - OTHER" },
  { code: "336411", description: "ONLINE ACCOUNTS" },
  { code: "336412", description: "ONLINE PAYMENTS" },
  { code: "336413", description: "AUTHENTICATING AND USER FEES" },
  { code: "336414", description: "CORPORATE ONLINE - OTHER" },
  { code: "336911", description: "BANK CHARGES - OTHER" },
  { code: "336919", description: "BANK CHARGES - OTHER" },
  { code: "337111", description: "CLIENT TRAVEL" },
  { code: "338111", description: "TEMPERATE CLOTHING ALLOWANCE" },
  { code: "338211", description: "OTHER CLOTHING (FBT)" },
  { code: "338311", description: "OTHER CLOTHING (NON-FBT)" },
  { code: "339111", description: "POSTAGE" },
  { code: "339211", description: "RADIO COMMUNICATIONS" },
  { code: "339311", description: "SEMI OFFICIAL TELEPHONES" },
  { code: "339411", description: "TELECOMS VOICE" },
  { code: "339412", description: "MOBILE PHONES" },
  { code: "339491", description: "PABX NETWORK VOICE" },
  { code: "339492", description: "NON-NETWORK VOICE" },
  { code: "339493", description: "MOBILES/SATELLITE PHONES" },
  { code: "339511", description: "ECO TELEPHONE CONTRIBUTIONS" },
  { code: "339911", description: "CARRIER CHARGES" },
  { code: "339912", description: "TELECOM HARDWARE UNDER $10000" },
  { code: "339913", description: "HARDWARE LEASES" },
  { code: "339914", description: "TRANSMISSION" },
  { code: "339915", description: "MAINTENANCE" },
  { code: "339916", description: "TIE CABLES" },
  { code: "339917", description: "USAGE" },
  { code: "339918", description: "CONNECTION CHARGES" },
  { code: "339921", description: "INSTALLATION" },
  { code: "339922", description: "PARTS" },
  { code: "339923", description: "RELOCATION" },
  { code: "339924", description: "DESIGN" },
  { code: "339925", description: "ANALYSIS" },
  { code: "339926", description: "OTHER" },
  { code: "339931", description: "DATEL" },
  { code: "339932", description: "ISDN - MACROLINK" },
  { code: "339933", description: "ISDN - MICROLINK" },
  { code: "339934", description: "FLEXNET" },
  { code: "339935", description: "INTERNET" },
  { code: "339936", description: "MEGALINK" },
  { code: "339937", description: "FRAME RELAY" },
  { code: "339938", description: "DDS" },
  { code: "339939", description: "INSTALLATION" },
  { code: "339941", description: "ROUTERS" },
  { code: "339942", description: "HUBS" },
  { code: "339943", description: "MODEMS/LINE DRIVERS" },
  { code: "339944", description: "SWITCHES" },
  { code: "339945", description: "SERVICERS" },
  { code: "339946", description: "CABLING" },
  { code: "339947", description: "LINES" },
  { code: "339948", description: "CONTROLLERS" },
  { code: "339949", description: "OTHER HARDWARE" },
  { code: "341111", description: "NON IT CONSULTANTS FEES - NT" },
  { code: "341911", description: "NON IT CONSULTANTS FEES - OTHER" },
  { code: "342111", description: "CONSUMABLES / GENERAL EXP" },
  { code: "342112", description: "TEA MAKING FACILITIES" },
  { code: "342113", description: "PEST ERADICATION" },
  { code: "342114", description: "MACHINE HIRE" },
  { code: "342115", description: "INDOOR PLANT HIRE" },
  { code: "342116", description: "RELOCATION EXPENSES" },
  { code: "342117", description: "PREPAID OUTGOINGS-INTERAGENCY" },
  { code: "342118", description: "EARLY INTERVENTION" },
  { code: "342119", description: "LATE FEES" },
  { code: "342119", description: "HOSPITALITY CLEARING ACCOUNT" },
  { code: "342299", description: "AMS PO ROUNDING" },
  { code: "344111", description: "DOCUMENT PRODUCTION" },
  { code: "346111", description: "EMPLOYEE & ASSOC (FBT)" },
  { code: "346211", description: "NON EMPLOYEE (NON-FBT)" },
  { code: "346311", description: "ENTERTAINMENT (NON-FBT)" },
  { code: "347111", description: "FEES & OTHER REGULATORY CHRG" },
  { code: "348111", description: "FOOD" },
  { code: "349111", description: "FREIGHT" },
  { code: "351111", description: "NETWORK CHARGES - SNA" },
  { code: "351121", description: "NETWORK CHARGES - SERVER" },
  { code: "351139", description: "SERVICE CENTRE FEE" },
  { code: "351149", description: "NETWORK MANAGEMENT FEE" },
  { code: "351211", description: "MONTHLYFIXED MAINFRAME EXPENSES" },
  { code: "351221", description: "APPLICATIONS SUPPORT CHARGES" },
  { code: "351311", description: "TELECOM INTERNET" },
  { code: "351319", description: "INTERNET (SP7)" },
  { code: "351321", description: "INTERNET TRAFFIC CHARGES" },
  { code: "351411", description: "DESKTOP SERVICES CHARGES" },
  { code: "351421", description: "MOVES/CHANGES & INSTALLATIONS" },
  { code: "351431", description: "OUT OF SCOPE CHARGES" },
  { code: "351491", description: "DESKTOP SERVICES CHRG - OTHER" },
  { code: "351499", description: "DESKTOP (SP3)" },
  { code: "351511", description: "MAILBOX SUBSCRIPTION/STORAGE" },
  { code: "351521", description: "DATABASE HOSTING/STORAGE" },
  { code: "351531", description: "COLLABORATION SERVICES/STORAGE" },
  { code: "351591", description: "MESSAGING CHARGES - OTHER" },
  { code: "351611", description: "DIAL UP SERVICES" },
  { code: "351621", description: "WAN ACCESS CHARGES" },
  { code: "351629", description: "DATA/WAN (SP6)" },
  { code: "351631", description: "MOVES/CHANGES & INSTALLATIONS" },
  { code: "351711", description: "SMALL SYSTEMS APPLICATIONS" },
  { code: "351721", description: "SPECIALIST SYSTEMS" },
  { code: "351731", description: "LOTUS NOTES" },
  { code: "351741", description: "WEB BASED" },
  { code: "351751", description: "ORACLE SERVICES" },
  { code: "351761", description: "MICROSOFT SUITE" },
  { code: "351791", description: "NON MAINFRAME APPLIC - OTHER" },
  { code: "351811", description: "LOTUS PRODUCTS LICENSING" },
  { code: "351891", description: "LICENSING CHARGES -  OTHER" },
  { code: "351911", description: "IT CHARGES - OTHER" },
  { code: "351912", description: "SECURITY ESCORTS" },
  { code: "351913", description: "INT SAN STORAGE AREA NETWORK" },
  { code: "351914", description: "INT SERVER HOSTING - CHAN" },
  { code: "351915", description: "INT SERVER MONITORING - CHAN OPS" },
  { code: "351916", description: "INT ENTERPRISE  BACKUP CHARGES" },
  { code: "351917", description: "INT PERFORMANCE REPORTING - MF SERVICES" },
  { code: "351918", description: "INT SLA MANAGEMENT" },
  { code: "351919", description: "INT EXPENSE ELIMINATION" },
  { code: "351921", description: "INT IT CHARGES - MIDRANGE" },
  { code: "351922", description: "INT IT CHARGES - MAINFRAME" },
  { code: "351923", description: "INT IT CHARGES - WOG" },
  { code: "351924", description: "INTERNAL IT EXPENSE ACCOUNT" },
  { code: "351925", description: "IT OVERHEADS" },
  { code: "351926", description: "INT IT CHARGES - DATA CENTRE OPERATIONS" },
  { code: "351927", description: "INT IT CHARGES - ENTERPRISE STORAGE" },
  { code: "351991", description: "INFRASTRUCTURE (SP8)" },
  { code: "352111", description: "DCS CONTRACTORS" },
  { code: "352112", description: "DCS CONTRACTOR REIMBURSEMENTS" },
  { code: "352113", description: "INTERNAL CONSULTING OFFSET ACC" },
  { code: "352121", description: "DCS INTERSTATE CONTRACTORS" },
  { code: "352122", description: "DCS INTERSTATE CONTRACTOR REIM" },
  { code: "352211", description: "DATA COMM CONSULTANTS" },
  { code: "352311", description: "INTERNET SERVICES CONSULTANTS" },
  { code: "352411", description: "DESKTOP SERVICES/LAN SERVICES" },
  { code: "352511", description: "MESSAGING CONSULTANTS" },
  { code: "352611", description: "IT STRATEGIC CONSULTANTS" },
  { code: "352711", description: "IT PROJECTS AND CONSULTING" },
  { code: "352811", description: "MAINFRAME APPS OUTSOURCING DMR" },
  { code: "352911", description: "NON DCS IT CONSULTANTS" },
  { code: "352912", description: "INT DCS CONSULTANT CHARGES" },
  { code: "352913", description: "OBIPS REPLACEMENT PROJECT" },
  { code: "353111", description: "OPERATING LEASE EXPENSES" },
  { code: "353911", description: "HARDWARE PURCHASES UNDER $10000" },
  { code: "353912", description: "ROUTERS" },
  { code: "353913", description: "HUBS" },
  { code: "353914", description: "MODEMS/LINE DRIVERS" },
  { code: "353915", description: "SWITHCES" },
  { code: "353916", description: "SERVERS" },
  { code: "353917", description: "DATA CABLES" },
  { code: "353918", description: "RACKS & POWER CABLES" },
  { code: "353921", description: "ROUTERS" },
  { code: "353922", description: "HUBS" },
  { code: "353923", description: "MODEMS/LINE DRIVERS" },
  { code: "353924", description: "SWITHCES" },
  { code: "353925", description: "SERVERS" },
  { code: "353926", description: "CABLING" },
  { code: "353927", description: "LINES" },
  { code: "353928", description: "CONTROLLERS" },
  { code: "353929", description: "IBM HARDWARE MAINTENANCE" },
  { code: "353931", description: "SOFTWARE PURCHASES UNDER $10000" },
  { code: "353932", description: "IBM MAINTENANCE & LICENCES" },
  { code: "353933", description: "THIRD PARTY MAINTENANCE & LICENCES" },
  { code: "353934", description: "SOFTWARE LICENCES UNDER $10000" },
  { code: "353935", description: "IBM MLC" },
  { code: "353936", description: "IBM PASSPORT ADVANTAGE" },
  { code: "353937", description: "IBM Z SW TOOLSET" },
  { code: "353938", description: "IBM DB2 AND MQ" },
  { code: "353939", description: "IBM OTHER" },
  { code: "354111", description: "SELF INSURANCE SCHEME" },
  { code: "354211", description: "GENERAL INSURANCE" },
  { code: "354311", description: "MOTOR VEHICLE INSURANCE" },
  { code: "354411", description: "PERSONAL ACCIDENT INSURANCE" },
  { code: "354511", description: "PROFESSIONAL INDEMNITY INS" },
  { code: "354611", description: "PUBLIC LIABILITY INS" },
  { code: "354711", description: "WORKERS' COMPENSATION INS" },
  { code: "354719", description: "WORKERS COMP ON-COSTS" },
  { code: "355111", description: "LABORATORY EXPENSES" },
  { code: "356111", description: "DEBT RECOVERY" },
  { code: "356211", description: "PUBLIC LIABILITY CLAIMS & EXP" },
  { code: "356311", description: "PROF INDEMNITY CLAIMS & EXP" },
  { code: "356411", description: "WITNESS EXPENSES" },
  { code: "356511", description: "SOLICITOR FEES" },
  { code: "356521", description: "BARRISTER FEES" },
  { code: "356531", description: "QUEEN'S COUNSEL FEES" },
  { code: "356541", description: "NON LEGAL FEES" },
  { code: "356551", description: "DISBURSEMENTS" },
  { code: "356591", description: "PROF FEES INTRASTATE - OTHER" },
  { code: "356611", description: "SOLICITOR FEES" },
  { code: "356621", description: "BARRISTER FEES" },
  { code: "356631", description: "QUEEN'S COUNSEL FEES" },
  { code: "356641", description: "NON LEGAL FEES" },
  { code: "356651", description: "DISBURSEMENTS" },
  { code: "356691", description: "PROF FEES INTERSTATE - OTHER" },
  { code: "356711", description: "SOLICITOR FEES" },
  { code: "356721", description: "BARRISTER FEES" },
  { code: "356731", description: "QUEEN'S COUNSEL FEES" },
  { code: "356741", description: "NON LEGAL FEES" },
  { code: "356751", description: "DISBURSEMENTS" },
  { code: "356791", description: "PROF FEES OVERSEAS - OTHER" },
  { code: "356811", description: "REPOSSESSION (EVICTION) EXP" },
  { code: "356821", description: "CONVEYANCING & SETTLEMENT FEE" },
  { code: "356831", description: "EX GRATIA PAYMENTS" },
  { code: "356851", description: "VICTIMS OF CRIME PAYMENTS" },
  { code: "356891", description: "LEGAL EXPENSES - OTHER" },
  { code: "357111", description: "LIBRARY SERVICES" },
  { code: "358111", description: "ADVERTISING" },
  { code: "358211", description: "MARKETING CONSULTANTS" },
  { code: "358311", description: "DISPLAYS" },
  { code: "358411", description: "EXHIBITIONS" },
  { code: "358911", description: "MARKETING & PROMOTION - OTHER" },
  { code: "359111", description: "MEDICAL/DENTAL SUPPLIES/SRVCS" },
  { code: "361111", description: "MEMBERSHIP AND SUBSCRIPTIONS" },
  { code: "362111", description: "VEHICLE OPERATING LEASE EXPENSES" },
  { code: "362211", description: "HIRE CHARGES" },
  { code: "362311", description: "FUEL" },
  { code: "362411", description: "ECO MOTOR VEHICLE CONTRIBUTIONS - PIPS POSTING " },
  { code: "362911", description: "MOTOR VEHICLE EXPENSES - OTHER" },
  { code: "363111", description: "OFFICE REQUISITES & STATIONERY" },
  { code: "363112", description: "COMPUTER STATIONERY" },
  { code: "364111", description: "INTRA TERRITORY FARES" },
  { code: "364211", description: "INTERSTATE FARES" },
  { code: "364311", description: "OVERSEAS FARES" },
  { code: "364411", description: "MEDICAL FARES" },
  { code: "364511", description: "AIR, BUS AND BOAT CHARTER" },
  { code: "364611", description: "ALLOW FOR USE OF EMPLOYEE'S MV" },
  { code: "364711", description: "CORPORATE TRAVEL PROVIDER FEES" },
  { code: "365111", description: "EQUIPMENT OPERATING LEASE EXPENSES" },
  { code: "365211", description: "HIRE CHARGES" },
  { code: "365911", description: "EQUIPMENT EXPENSES - OTHER" },
  { code: "365912", description: "PURCHASE FURNITURE & FITTINGS" },
  { code: "365913", description: "REPAIRS & MAINTENANCE - GENERAL" },
  { code: "366111", description: "RECRUITMENT ADVERTISING" },
  { code: "366211", description: "RECRUITMENT FARES" },
  { code: "366311", description: "REMOVAL AND STORAGE EXPENSES" },
  { code: "366411", description: "RELOCATION ALLOWANCE" },
  { code: "366911", description: "RECRUITMENT EXPENSES - OTHER" },
  { code: "367111", description: "AFFILIATION FEES" },
  { code: "367211", description: "AIR FARES" },
  { code: "367311", description: "SITTING FEES - PIPS POSTING LEVEL" },
  { code: "367312", description: "SITTING FEES - SALARY SACRIFICE" },
  { code: "367411", description: "ACCOMMODATION" },
  { code: "367911", description: "BOARD/COMMITTEE EXP - OTHER" },
  { code: "368111", description: "RELOCATION FARES" },
  { code: "368211", description: "REMOVAL AND STORAGE EXPENSES" },
  { code: "368311", description: "RELOCATION ALLOWANCE" },
  { code: "368911", description: "RELOCATION EXPENSES - OTHER" },
  { code: "371111", description: "HECS" },
  { code: "371911", description: "TUITION FEES" },
  { code: "371912", description: "TA - TRAINING & STUDY" },
  { code: "371913", description: "FARES - TRAINING & STUDY" },
  { code: "371914", description: "OTHER - VENUE HIRE" },
  { code: "371915", description: "SEMINARS" },
  { code: "371916", description: "HIGHER EDUCATION FEES" },
  { code: "372111", description: "OPERATING LEASE EXPENSES" },
  { code: "372211", description: "HIRE CHARGES" },
  { code: "372311", description: "FUEL" },
  { code: "372911", description: "TRANSPORT EQUIPMENT  - OTHER" },
  { code: "373111", description: "INTRA TERRITORY TA" },
  { code: "373211", description: "INTERSTATE TA" },
  { code: "373311", description: "OVERSEAS TA" },
  { code: "374111", description: "DISPUTED CORPORATE CREDIT CARD PURCHASES" },
  { code: "374211", description: "UNALLOCATED CREDIT CARD PURCHASES" },
  { code: "375111", description: "PENALTY INTEREST ON LATE PAYMENTS" },
  { code: "377111", description: "REVALUATION ADJUSTMENTS-LONG TERM LIABILITIES" },
  { code: "378111", description: "PURCHASES OF GOODS AND SERVICES -NON-CASH" },
  { code: "378211", description: "PURCH GOODS&SERVS-LEASE CONTRA" },
  { code: "379111", description: "GOODS & SERVICES COST ALLOC" },
  { code: "381111", description: "DEPRECIATION" },
  { code: "381115", description: "LEASED BUILDING-DEPN EXP" },
  { code: "381116", description: "DEPRECIATION EXP ASSET ACCOUNTING" },
  { code: "381117", description: "DEPRECIATION EXPENSE INFRASTRUCTURE" },
  { code: "381211", description: "AMORTISATION" },
  { code: "381215", description: "LEASED-BUILDING-AMORTISATION" },
  { code: "381311", description: "AMORTISATION OF LEASED ASSETS" },
  { code: "382111", description: "ASSET REVALUATION" },
  { code: "382211", description: "ASSETS WRITTEN DOWN" },
  { code: "382311", description: "INVENTORIES WRITTEN OFF" },
  { code: "382911", description: "ASSETS WRITTEN OFF - OTHER" },
  { code: "383111", description: "ASSETS DONATED AND GIFTED - LAND" },
  { code: "383211", description: "ASSETS DONATED AND GIFTED - BUILDINGS" },
  { code: "383311", description: "ASSETS DONATED AND GIFTED \u2013 INFRASTRUCTURE ASSETS" },
  { code: "383411", description: "ASSETS DONATED AND GIFTED - PLANT AND EQUIPMENT" },
  { code: "383511", description: "ASSETS DONATED AND GIFTED \u2013 COMPUTER SOFTWARE" },
  { code: "383611", description: "ASSETS DONATED AND GIFTED \u2013 COMPUTER HARDWARE" },
  { code: "383711", description: "ASSETS DONATED AND GIFTED \u2013 TRANSPORT EQUIPMENT" },
  { code: "383811", description: "ASSETS DONATED AND GIFTED \u2013 CULTURAL ASSETS" },
  { code: "383911", description: "ASSETS DONATED AND GIFTED \u2013 INTANGIBLE ASSETS" },
  { code: "393111", description: "CONSOLIDATED REV ACCT ON-COSTS" },
  { code: "394111", description: "DOUBTFUL DEBTS EXPENSE - AGENCY AR" },
  { code: "395111", description: "ADVANCES WRITTEN OFF" },
  { code: "395211", description: "BAD DEBTS" },
  { code: "395311", description: "LOANS WRITTEN OFF" },
  { code: "395411", description: "LOSSES OF MONEY" },
  { code: "395511", description: "ADVANCES WRITTEN DOWN" },
  { code: "395711", description: "BAD DEBTS - TAXES RECEIVABLE" },
  { code: "398111", description: "DBE GOODS & SRVC REC FOC" },
  { code: "398211", description: "AGENCY GOODS & SRVC REC FOC" },
  { code: "399111", description: "INCOME TAX EXPENSE" },
  { code: "411111", description: "CURRENT GRANTS" },
  { code: "411511", description: " TO CHARITIES/NON PROFIT ORGS" },
  { code: "412111", description: "CAPITAL GRANTS" },
  { code: "412511", description: "TO CHARITIES / NON PROFIT" },
  { code: "413111", description: "CURRENT SUBSIDIES" },
  { code: "413211", description: "PERSONAL BENEFITS" },
  { code: "414111", description: "CURRENT CSO" },
  { code: "414211", description: "CAPITAL CSO" },
  { code: "415111", description: "LOTTERY RECEIPTS - CRA" },
  { code: "415121", description: "LOTTERY REC - SPORTS/REC DEVT" },
  { code: "511111", description: "INTEREST EXPENSE" },
  { code: "512111", description: "FINANCE LEASE INTEREST" },
  { code: "531111", description: "CAPITAL USE CHARGE" },
  { code: "611111", description: "ADVANCE TO THE TREASURER" },
  { code: "811111", description: "MAIN ACCOUNT" },
  { code: "811121", description: "ADVANCE ACCOUNTS" },
  { code: "811131", description: "EXTERNAL WITHIN SET OFF GROUP" },
  { code: "811141", description: "EXTERNAL OUTSIDE SET OFF GROUP" },
  { code: "811211", description: "CASH FLOATS " },
  { code: "811221", description: "CASH IN TRANSIT" },
  { code: "812111", description: "ACCOUNTS RECEIVABLE" },
  { code: "812112", description: "ACCOUNTS RECEIVABLE DCS BILLING" },
  { code: "812121", description: "ALLOWANCE FOR DOUBTFUL DEBTS" },
  { code: "812122", description: "ADJUSTMENTS" },
  { code: "812211", description: "TAXES RECEIVABLE" },
  { code: "812331", description: "CURRENT GRANTS & SUBSIDIES REC" },
  { code: "812341", description: "CAPITAL GRANTS & SUBSIDIES REC" },
  { code: "812411", description: "INTEREST RECEIVABLE" },
  { code: "812511", description: "ROYALTIES AND RENTS RECEIVABLE" },
  { code: "812711", description: "OUTPUT RECEIVABLE" },
  { code: "812721", description: "CSO RECEIVABLE" },
  { code: "812811", description: "GST DUE / RECEIVED" },
  { code: "812812", description: "WHOLE OF INVOICE DUE/RECEIVED" },
  { code: "812821", description: "GST OWING / PAID" },
  { code: "812822", description: "100% GET INVOICE" },
  { code: "812831", description: "GST ADJUSTMENTS - ACQUISITIONS" },
  { code: "812841", description: "GST ADJUSTMENTS - SUPPLIES" },
  { code: "812851", description: "GST ADJ - CREDITABLE PURPOSE" },
  { code: "812881", description: "OTHER GST GROUP REG ENTITIES" },
  { code: "812891", description: "ATO PAYMENTS / REFUNDS" },
  { code: "812899", description: "GST OPENING BALANCE" },
  { code: "812911", description: "RECEIVABLES - OTHER" },
  { code: "812951", description: "UNAUTHORISED CREDIT CARD PURCHASES" },
  { code: "813111", description: "ACCRUED REVENUE" },
  { code: "814111", description: "INVENTORY PURCHASES" },
  { code: "815111", description: "SALARY ADVANCES - PIPS POSTING LEVEL" },
  { code: "815911", description: "SOFTWARE LICENCE & MAINTENANCE" },
  { code: "815912", description: "FINANCE LEASE " },
  { code: "815913", description: "PREPAID EXPENSES OTHER" },
  { code: "815921", description: "PREPAID GENERAL INSURANCE" },
  { code: "815922", description: "PREPAID VEHICLE INSURANCE" },
  { code: "815923", description: "PREPAID WORKERS COMPENSATION INSURANCE" },
  { code: "815931", description: "IBM HARDWARE MAINTENANCE" },
  { code: "815935", description: "IBM CBA TRACKER" },
  { code: "815936", description: "IBM PASSPORT ADVANTAGE" },
  { code: "815937", description: "IBM Z SW TOOLSET" },
  { code: "815938", description: "IBM DB2 AND MQ" },
  { code: "815939", description: "IBM OTHER" },
  { code: "815941", description: "PREPAID SOFTWARE LICENCE AND CHARGES" },
  { code: "815942", description: "PREPAID SOFTWARE OTHER" },
  { code: "815999", description: "PREPAID CLEARING ACCOUNT" },
  { code: "817111", description: "ADVANCES PAID" },
  { code: "817121", description: "ADVANCES REPAID" },
  { code: "817131", description: "ADVANCES WRITTEN OFF" },
  { code: "817211", description: "ALLOWANCE FOR DOUBTFUL ADVANCE" },
  { code: "818111", description: "PURCHASES" },
  { code: "818121", description: "DISPOSALS" },
  { code: "818131", description: "TRANSFERS IN/OUT" },
  { code: "818141", description: "REVALUATION" },
  { code: "821111", description: "DEFERRED INCOME TAX ASSETS" },
  { code: "821211", description: "CRCA SUSPENSE ACCT" },
  { code: "821221", description: "LTF SUSPENSE ACCT" },
  { code: "821231", description: "GAS SUSPENSE ACCT" },
  { code: "822111", description: "LEASE RECEIVABLE - PURCHASES" },
  { code: "822121", description: "LEASE RECEIVABLE - REPAID" },
  { code: "822131", description: "LEASE RECEIVABLE - TRANSFER IN/OUT" },
  { code: "822141", description: "LEASE RECEIVABLE - INCREMENT/DECREMENT" },
  { code: "822171", description: "LEASE RECEIVABLE - IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "831111", description: "ACCOUNTS RECEIVABLE" },
  { code: "831121", description: "ALLOWANCE FOR DOUBTFUL DEBTS" },
  { code: "831211", description: "TAXES RECEIVABLE" },
  { code: "831311", description: "CURRENT" },
  { code: "831321", description: "CAPITAL" },
  { code: "831411", description: "INTEREST RECEIVABLE" },
  { code: "831911", description: "RECEIVABLES OTHER" },
  { code: "832111", description: "PREPAID EXPENSES - NON CURRENT" },
  { code: "834111", description: "ADVANCES PAID" },
  { code: "834121", description: "ADVANCES REPAID" },
  { code: "834141", description: "ADVANCES WRITTEN OFF NON CURRENT" },
  { code: "834151", description: "ADVANCES WRITTEN DOWN NON CURRENT" },
  { code: "835111", description: "CAPITAL APPROPRIATION - NON CURRENT" },
  { code: "835121", description: "DISPOSAL" },
  { code: "835131", description: "EQUITY TRANSFER IN - NON CASH" },
  { code: "835132", description: "EQUITY TRANSFER IN - CASH" },
  { code: "835133", description: "EQUITY TRANSFER OUT - NON CASH" },
  { code: "835134", description: "EQUITY TRANSFER OUT - CASH" },
  { code: "835141", description: "REVAL INCREMENT/DECREMENT" },
  { code: "836111", description: "DEFERRED INCOME TAX ASSETS - NON CURRENT" },
  { code: "841111", description: "ACQUISITIONS" },
  { code: "841121", description: "SALES" },
  { code: "841131", description: "TRANSFERS IN" },
  { code: "841141", description: "TRANSFERS OUT" },
  { code: "841151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "842111", description: "ACQUISITIONS" },
  { code: "842112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "842121", description: "SALES" },
  { code: "842131", description: "TRANSFERS IN" },
  { code: "842132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "842141", description: "TRANSFERS OUT" },
  { code: "842151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "842161", description: "CAPITALISED EXPENDITURE" },
  { code: "842171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "842211", description: "CURRENT DEPRECIATION" },
  { code: "842221", description: "SALES" },
  { code: "842231", description: "TRANSFERS" },
  { code: "842241", description: "REVAL DEPREC ADJUSTMENTS" },
  { code: "842271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "843111", description: "ACQUISITIONS" },
  { code: "843112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "843121", description: "SALES" },
  { code: "843131", description: "TRANSFERS IN" },
  { code: "843132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "843141", description: "TRANSFERS OUT" },
  { code: "843151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "843161", description: "CAPITALISED EXPENDITURE" },
  { code: "843171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "843211", description: "CURRENT DEPRECIATION" },
  { code: "843221", description: "SALES" },
  { code: "843231", description: "TRANSFERS" },
  { code: "843241", description: "REVAL DEPREC ADJUSTMENTS" },
  { code: "843271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "844111", description: "ACQUISITIONS" },
  { code: "844121", description: "TRANSFERS IN" },
  { code: "844131", description: "TRANSFERS OUT" },
  { code: "844141", description: "CAPITALISED EXPENDITURE" },
  { code: "844211", description: "ACQUISITIONS" },
  { code: "844221", description: "TRANSFERS IN" },
  { code: "844231", description: "TRANSFERS OUT" },
  { code: "844241", description: "CAPITALISED EXPENDITURE" },
  { code: "845111", description: "ACQUISITIONS" },
  { code: "845112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "845115", description: "LEASED BUILDING-ACQUISTIONS" },
  { code: "845119", description: "ASSET CLEARING ACCOUNT" },
  { code: "845121", description: "SALES" },
  { code: "845125", description: "LEASED BUILDING-SALES" },
  { code: "845131", description: "TRANSFERS IN" },
  { code: "845132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "845135", description: "LEASED BUILDING-TRANSFER IN" },
  { code: "845141", description: "TRANSFERS OUT" },
  { code: "845145", description: "LEASED BUILDING-TRANSFER OUT" },
  { code: "845151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "845155", description: "LEASED BUILDING-REVAL" },
  { code: "845161", description: "CAPITALISED EXPENDITURE" },
  { code: "845165", description: "LEASED BUILDING-CAPITALISED EXP" },
  { code: "845171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "845211", description: "CURRENT DEPRECIATION" },
  { code: "845215", description: "LEASED BUILDING-CURRENT DEPN" },
  { code: "845221", description: "SALES" },
  { code: "845225", description: "LEASED BUILDING-SALES" },
  { code: "845231", description: "TRANSFERS" },
  { code: "845235", description: "LEASED BUILDING-TRANSFERS" },
  { code: "845241", description: "REVAL DEPREC ADJUSTMENTS" },
  { code: "845245", description: "LEASED BUILDING-REVAL" },
  { code: "845271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "846111", description: "ACQUISITIONS" },
  { code: "846112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "846121", description: "SALES" },
  { code: "846131", description: "TRANSFERS IN" },
  { code: "846132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "846141", description: "TRANSFERS OUT" },
  { code: "846151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "846161", description: "CAPITALISED EXPENDITURE" },
  { code: "846171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "846211", description: "CURRENT AMORTISATION" },
  { code: "846221", description: "SALES" },
  { code: "846231", description: "TRANSFERS" },
  { code: "846241", description: "REVAL AMORT ADJUSTMENTS" },
  { code: "846271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "847111", description: "ACQUISITIONS" },
  { code: "847112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "847121", description: "SALES" },
  { code: "847131", description: "TRANSFERS IN" },
  { code: "847132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "847141", description: "TRANSFERS OUT" },
  { code: "847151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "847161", description: "CAPITALISED EXPENDITURE" },
  { code: "847171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "847211", description: "CURRENT DEPRECIATION" },
  { code: "847221", description: "SALES" },
  { code: "847231", description: "TRANSFERS" },
  { code: "847241", description: "REVAL DEPREC ADJUSTMENTS" },
  { code: "847271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "848111", description: "ACQUISITIONS" },
  { code: "848112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "848121", description: "SALES" },
  { code: "848131", description: "TRANSFERS IN" },
  { code: "848132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "848141", description: "TRANSFERS OUT" },
  { code: "848151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "848161", description: "CAPITALISED EXPENDITURE" },
  { code: "848171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "848211", description: "CURRENT DEPRECIATION" },
  { code: "848221", description: "SALES" },
  { code: "848231", description: "TRANSFERS" },
  { code: "848241", description: "REVAL DEPREC ADJUSTMENTS" },
  { code: "848271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "849111", description: "ACQUISITIONS" },
  { code: "849112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "849121", description: "SALES" },
  { code: "849131", description: "TRANSFERS IN" },
  { code: "849132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "849141", description: "TRANSFERS OUT" },
  { code: "849151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "849161", description: "CAPITALISED EXPENDITURE" },
  { code: "849171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "849211", description: "CURRENT DEPRECIATION" },
  { code: "849221", description: "SALES" },
  { code: "849231", description: "TRANSFERS" },
  { code: "849241", description: "REVAL DEPREC ADJUSTMENTS" },
  { code: "849271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "851111", description: "ACQUISITIONS" },
  { code: "851112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "851121", description: "SALES" },
  { code: "851131", description: "TRANSFERS IN" },
  { code: "851132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "851141", description: "TRANSFERS OUT" },
  { code: "851151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "851161", description: "CAPITALISED EXPENDITURE" },
  { code: "851171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "851211", description: "CURRENT AMORTISATION" },
  { code: "851221", description: "SALES" },
  { code: "851231", description: "TRANSFERS" },
  { code: "851241", description: "REVAL AMORT ADJUSTMENTS" },
  { code: "851271", description: "ACCUM DEPN-IMPAIRMENT ADJUSTMENT" },
  { code: "861111", description: "ACQUISITIONS" },
  { code: "861112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "861121", description: "SALES" },
  { code: "861131", description: "TRANSFERS IN" },
  { code: "861132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "861141", description: "TRANSFERS OUT" },
  { code: "861151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "861161", description: "CAPITALISED EXPENDITURE" },
  { code: "861171", description: "ASSET IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "871111", description: "LAND UNDER FINANCE LEASE - ACQUISITION" },
  { code: "871131", description: "LAND UNDER FINANCE LEASE - TRANSFER IN" },
  { code: "871141", description: "LAND UNDER FINANCE LEASE - TRANSFER OUT" },
  { code: "871151", description: "LAND UNDER FINANCE LEASE - REVALUATION INCREMENT/DECREMENT" },
  { code: "871171", description: "LAND UNDER FINANCE LEASE - IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "871181", description: "LAND UNDER LEASE - INITIAL RECOGNITION" },
  { code: "871191", description: "LAND UNDER LEASE - ACQUISITIONS" },
  { code: "871211", description: "CURRENT AMORTISATION - LAND UNDER FINANCE LEASE" },
  { code: "871231", description: "ACCUMULATED AMORTISATION - LAND UNDER FINANCE LEASE - TRANSFERS" },
  { code: "871241", description: "ACCUMULATED AMORTISATION - LAND UNDER FINANCE LEASE - REVALUATION ADJUSTMENTS" },
  { code: "871271", description: "ACCUMULATED AMORTISATION - LAND UNDER FINANCE LEASE - IMPAIRMENT ADJUSTMENTS" },
  { code: "875111", description: "ACQUISITIONS" },
  { code: "875112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "875121", description: "SALES" },
  { code: "875131", description: "TRANSFERS IN" },
  { code: "875132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "875141", description: "TRANSFERS OUT" },
  { code: "875151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "875161", description: "CAPITALISED EXPENDITURE" },
  { code: "875171", description: "IMPAIRMENT DECREMENT/REVERSAL" },
  { code: "875181", description: "PLANT AND EQUIPMENT UNDER LEASE - INITIAL RECOGNITION" },
  { code: "875191", description: "PLANT AND EQUIPMENT UNDER LEASE - ACQUISITIONS" },
  { code: "875211", description: "CURRENT AMORTISATION" },
  { code: "875221", description: "SALES" },
  { code: "875231", description: "TRANSFERS" },
  { code: "875241", description: "REVAL AMORT ADJUSTMENTS" },
  { code: "875271", description: "IMPAIRMENT ADJUSTMENTS" },
  { code: "876111", description: "ACQUISITIONS" },
  { code: "876112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "876121", description: "SALES" },
  { code: "876131", description: "TRANSFERS IN" },
  { code: "876132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "876141", description: "TRANSFERS OUT" },
  { code: "876151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "876161", description: "CAPITALISED EXPENDITURE" },
  { code: "876191", description: "COMPUTER SOFTWARE UNDER LEASE - ACQUISITIONS" },
  { code: "876211", description: "CURRENT AMORTISATION" },
  { code: "876221", description: "SALES" },
  { code: "876231", description: "TRANSFERS" },
  { code: "876241", description: "REVAL AMORT ADJUSTMENTS" },
  { code: "877111", description: "ACQUISITIONS" },
  { code: "877112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "877121", description: "SALES" },
  { code: "877131", description: "TRANSFERS IN" },
  { code: "877132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "877141", description: "TRANSFERS OUT" },
  { code: "877151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "877161", description: "CAPITALISED EXPENDITURE" },
  { code: "877191", description: "COMPUTER HARDWARE UNDER LEASE - ACQUISITIONS" },
  { code: "877211", description: "CURRENT AMORTISATION" },
  { code: "877221", description: "SALES" },
  { code: "877231", description: "TRANSFERS" },
  { code: "877241", description: "REVAL AMORT ADJUSTMENTS" },
  { code: "878111", description: "ACQUISITIONS" },
  { code: "878112", description: "INTRA AGENCY MOVEMENTS" },
  { code: "878121", description: "SALES" },
  { code: "878131", description: "TRANSFERS IN" },
  { code: "878132", description: "INTRA AGENCY MOVEMENTS" },
  { code: "878141", description: "TRANSFERS OUT" },
  { code: "878151", description: "REVAL INCREMENT/DECREMENT" },
  { code: "878161", description: "CAPITALISED EXPENDITURE" },
  { code: "878181", description: "TRANSPORT EQUIPMENT UNDER LEASE - INITIAL RECOGNITION" },
  { code: "878191", description: "TRANSPORT EQUIPMENT UNDER LEASE - ACQUISITIONS" },
  { code: "878211", description: "CURRENT AMORTISATION" },
  { code: "878221", description: "SALES" },
  { code: "878231", description: "TRANSFERS" },
  { code: "878241", description: "REVAL AMORT ADJUSTMENTS" },
  { code: "911111", description: "RECEIPTS - AOTA" },
  { code: "911151", description: "EXPENSES - AOTA" },
  { code: "911211", description: "RECEIPTS - CLEARING" },
  { code: "911511", description: "EXPENSES - CLEARING" },
  { code: "912111", description: "ACCOUNTS PAYABLE CONTROL" },
  { code: "912121", description: "PURCHASE ORDER CONTROL" },
  { code: "912191", description: "CREDIT CARD CONTROL" },
  { code: "912211", description: "CURRENT GRANTS PAYABLE" },
  { code: "912221", description: "CAPITAL GRANTS PAYABLE" },
  { code: "912231", description: "CURRENT SUBSIDIES PAYABLE" },
  { code: "912241", description: "CAPITAL SUBSIDIES PAYABLE" },
  { code: "912311", description: "INTEREST PAYABLE" },
  { code: "912411", description: "NO ABN WITHHELD" },
  { code: "912412", description: "NO ABN PAYMENT TO ATO" },
  { code: "912421", description: "VOLUNTARY AGREEMENT WITHHELD" },
  { code: "912422", description: "VOLUNTARY AGREEMENT PAYMENT TO ATO" },
  { code: "912431", description: "FOREIGN RESIDENT CAPITAL GAINS WITHHELD" },
  { code: "912432", description: "FOREIGN RESIDENT CAPITAL GAINS PAYMENT TO ATO" },
  { code: "912491", description: "PAYG WITHHOLDING - OTHER" },
  { code: "912521", description: "COMM/GOVT SERVICE OBLIGATIONS" },
  { code: "912711", description: "AP - PROPERTY, PLANT & EQUIP" },
  { code: "913111", description: "ACCRUED SALARIES - PIPS POSTING LEVEL" },
  { code: "913911", description: "RENT" },
  { code: "913912", description: "COMMUNICATIONS" },
  { code: "913913", description: "AUDIT FEES" },
  { code: "913914", description: "SUPERANNUATION" },
  { code: "913915", description: "OTHER" },
  { code: "913916", description: "GOVT SERVICE LEVEL AGREEMENTS" },
  { code: "913917", description: "POWER" },
  { code: "913918", description: "IT CHARGES" },
  { code: "913919", description: "CONSULTANTS" },
  { code: "914111", description: "UNEARNED REVENUE - CHARGES" },
  { code: "914211", description: "UNEARNED REV - CAPITAL CONTRIB" },
  { code: "914811", description: "UNEARNED REVENUE - ASSET SALES" },
  { code: "914911", description: "UNEARNED REVENUE - OTHER" },
  { code: "915111", description: "RECREATION LEAVE - PIPS POSTING LEVEL" },
  { code: "915211", description: "LONG SERVICE LEAVE - PIPS POSTING LEVEL" },
  { code: "915311", description: "RECREATION LEAVE LOADING - PIPS POSTING LEVEL" },
  { code: "915411", description: "RECREATION LEAVE FARES" },
  { code: "915511", description: "PURCHASED RECREATION LEAVE - PIPS POSTING LEVEL" },
  { code: "915611", description: "EXTENDED LEVEL (5 YEAR SCHEME) - PIPS POSTING LEVEL" },
  { code: "916111", description: "INTERIM DIVIDEND" },
  { code: "916211", description: "FINAL DIVIDEND" },
  { code: "916311", description: "FRINGE BENEFITS TAX" },
  { code: "916411", description: "INCOME TAX" },
  { code: "916511", description: "PAYROLL TAX" },
  { code: "916519", description: "PAYROLL TAX ON-COSTS" },
  { code: "916611", description: "DEFERRED INCOME TAX" },
  { code: "916711", description: "EMPLOYER SUPER CONTRIB" },
  { code: "916712", description: "EMPLOYER SUPER ON-COSTS" },
  { code: "916721", description: "SUPER ON COSTS COF" },
  { code: "916722", description: "SUPER ON COSTS NON-COF" },
  { code: "916723", description: "ACC SAL SUPER ON COSTS COF" },
  { code: "916724", description: "ACC SAL SUPER ON COSTS NON-COF" },
  { code: "916811", description: "WORKERS COMP PREMIUMS" },
  { code: "916819", description: "WORKERS COMP ON-COSTS" },
  { code: "916911", description: "PROVISIONS - OTHER" },
  { code: "917111", description: "LOANS RECEIVED" },
  { code: "917121", description: "LOANS REPAID" },
  { code: "917211", description: "SECURITIES" },
  { code: "918111", description: "PLANT AND EQUIPMENT" },
  { code: "918211", description: "COMPUTER SOFTWARE" },
  { code: "918311", description: "COMPUTER HARDWARE" },
  { code: "918411", description: "TRANSPORT EQUIPMENT" },
  { code: "918811", description: "LAND FINANCIAL LEASE LIABILITY" },
  { code: "919111", description: "ADVANCES RECEIVED" },
  { code: "919121", description: "ADVANCES REPAID" },
  { code: "924111", description: "PLANT AND EQUIPMENT LEASE LIABILITY - RECEIVED" },
  { code: "924121", description: "PLANT AND EQUIPMENT LEASE LIABILITY - REPAID" },
  { code: "924131", description: "PLANT AND EQUIPMENT LEASE LIABILITY - TRANSFERS IN/OUT" },
  { code: "924141", description: "PLANT AND EQUIPMENT LEASE LIABILITY - INCREMENT/DECREMENT" },
  { code: "924151", description: "PLANT AND EQUIPMENT LEASE LIABILITY - TRANSITION" },
  { code: "924411", description: "TRANSPORT EQUIPMENT LEASE LIABILITY - RECEIVED" },
  { code: "924421", description: "TRANSPORT EQUIPMENT LEASE LIABILITY - REPAID" },
  { code: "924431", description: "TRANSPORT EQUIPMENT LEASE LIABILITY - TRANSFERS IN/OUT" },
  { code: "924441", description: "TRANSPORT EQUIPMENT LEASE LIABILITY - INCREMENT/DECREMENT" },
  { code: "924451", description: "TRANSPORT EQUIPMENT LEASE LIABILITY - TRANSITION" },
  { code: "924511", description: "BUILDING LEASE LIABILITY - RECEIVED" },
  { code: "924521", description: "BUILDING LEASE LIABILITY - REPAID" },
  { code: "924531", description: "BUILDING LEASE LIABILITY - TRANSFERS IN/OUT" },
  { code: "924541", description: "BUILDING LEASE LIABILITY - INCREMENT/DECREMENT" },
  { code: "924551", description: "BUILDING LEASE LIABILITY - TRANSITION" },
  { code: "924711", description: "INFRASTRUCTURE LEASE LIABILITY - RECEIVED" },
  { code: "924721", description: "INFRASTRUCTURE LEASE LIABILITY - REPAID" },
  { code: "924731", description: "INFRASTRUCTURE LEASE LIABILITY - TRANSFERS IN/OUT" },
  { code: "924741", description: "INFRASTRUCTURE LEASE LIABILITY - INCREMENT/DECREMENT" },
  { code: "924751", description: "INFRASTRUCTURE LEASE LIABILITY - TRANSITION" },
  { code: "924811", description: "LAND LEASE LIABILITY - RECEIVED" },
  { code: "924821", description: "LAND LEASE LIABILITY - REPAID" },
  { code: "924831", description: "LAND LEASE LIABILITY - TRANSFERS IN/OUT" },
  { code: "924841", description: "LAND LEASE LIABILITY - INCREMENT/DECREMENT" },
  { code: "924851", description: "LAND LEASE LIABILITY - TRANSITION" },
  { code: "931111", description: "ACCOUNTS" },
  { code: "931211", description: "CURRENT GRANTS PAYABLE - NON CURRENT" },
  { code: "931221", description: "CAPITAL GRANTS PAYABLE - NON CURRENT" },
  { code: "931231", description: "CURRENT SUBSIDIES PAYABLE - NON CURRENT" },
  { code: "931241", description: "CAPITAL SUBSIDIES PAYABLE - NON CURRENT" },
  { code: "931311", description: "AP - PROPERTY, PLANT & EQUIP" },
  { code: "932911", description: "OTHER UNEARNED REVENUE" },
  { code: "933111", description: "LONG SERVICE LEAVE" },
  { code: "933211", description: "RECREATION LEAVE" },
  { code: "933311", description: "PURCHASED RECREATION LEAVE " },
  { code: "933411", description: "EXTENDED LEAVE (5 YEAR SCHEME) " },
  { code: "934111", description: "DEFERRED INCOME TAX" },
  { code: "935111", description: "LOANS RECEIVED" },
  { code: "935121", description: "LOANS REPAID" },
  { code: "935211", description: "SECURITIES" },
  { code: "936111", description: "PLANT AND EQUIPMENT" },
  { code: "936211", description: "COMPUTER SOFTWARE" },
  { code: "936311", description: "COMPUTER HARDWARE" },
  { code: "936411", description: "TRANSPORT EQUIPMENT" },
  { code: "936811", description: "LAND FINANCIAL LEASE LIABILITY - NON CURRENT" },
  { code: "937111", description: "ADVANCES RECEIVED" },
  { code: "937121", description: "ADVANCES REPAID" },
  { code: "941111", description: "PLANT AND EQUIPMENT LEASE LIABILITY NON CURRENT - RECEIVED" },
  { code: "941121", description: "PLANT AND EQUIPMENT LEASE LIABILITY NON CURRENT - REPAID" },
  { code: "941131", description: "PLANT AND EQUIPMENT LEASE LIABILITY NON CURRENT - TRANSFERS IN/OUT" },
  { code: "941141", description: "PLANT AND EQUIPMENT LEASE LIABILITY NON CURRENT - INCREMENT/DECREMENT" },
  { code: "941151", description: "PLANT AND EQUIPMENT LEASE LIABILITY NON CURRENT - TRANSITION" },
  { code: "941411", description: "TRANSPORT EQUIPMENT LEASE LIABILITY NON CURRENT - RECEIVED" },
  { code: "941421", description: "TRANSPORT EQUIPMENT LEASE LIABILITY NON CURRENT - REPAID" },
  { code: "941431", description: "TRANSPORT EQUIPMENT LEASE LIABILITY NON CURRENT - TRANSFERS IN/OUT" },
  { code: "941441", description: "TRANSPORT EQUIPMENT LEASE LIABILITY NON CURRENT - INCREMENT/DECREMENT" },
  { code: "941451", description: "TRANSPORT EQUIPMENT LEASE LIABILITY NON CURRENT - TRANSITION" },
  { code: "941511", description: "BUILDING LEASE LIABILITY NON CURRENT - RECEIVED" },
  { code: "941521", description: "BUILDING LEASE LIABILITY NON CURRENT - REPAID" },
  { code: "941531", description: "BUILDING LEASE LIABILITY NON CURRENT - TRANSFERS IN/OUT" },
  { code: "941541", description: "BUILDING LEASE LIABILITY NON CURRENT - INCREMENT/DECREMENT" },
  { code: "941551", description: "BUILDING LEASE LIABILITY NON CURRENT  - TRANSITION" },
  { code: "941711", description: "INFRASTRUCTURE LEASE LIABILITY NON CURRENT - RECEIVED" },
  { code: "941721", description: "INFRASTRUCTURE LEASE LIABILITY NON CURRENT - REPAID" },
  { code: "941731", description: "INFRASTRUCTURE LEASE LIABILITY NON CURRENT - TRANSFERS IN/OUT" },
  { code: "941741", description: "INFRASTRUCTURE LEASE LIABILITY NON CURRENT - INCREMENT/DECREMENT" },
  { code: "941751", description: "INFRASTRUCTURE LEASE LIABILITY NON CURRENT - TRANSITION" },
  { code: "941811", description: "LAND LEASE LIABILITY NON CURRENT - RECEIVED" },
  { code: "941821", description: "LAND LEASE LIABILITY NON CURRENT - REPAID" },
  { code: "941831", description: "LAND LEASE LIABILITY NON CURRENT - TRANSFERS IN/OUT" },
  { code: "941841", description: "LAND LEASE LIABILITY NON CURRENT - INCREMENT/DECREMENT" },
  { code: "941851", description: "LAND LEASE LIABILITY NON CURRENT - TRANSITION" },
  { code: "13111A", description: "COMMERCIAL WORKS" },
  { code: "13111B", description: "DIAL UP" },
  { code: "13111C", description: "MAINFRAME SNA CONNECTIONS" },
  { code: "13111D", description: "TRANSMISSION" },
  { code: "13111E", description: "DCS TRAINING SERVICES" },
  { code: "13111F", description: "HUMAN RESOURCE CHG" },
  { code: "13111G", description: "DCS INTERNAL TIME & MATERIALS SERVICES" },
  { code: "13111H", description: "LOTUS NOTES LICENCES" },
  { code: "13111i", description: "DCS INTERNAL TIME & MATERIALS SERVICES" },
  { code: "13111J", description: "SITE MANAGEMENT" },
  { code: "13111K", description: "MIDRANGE OPERATING SYSTEMS SUPPORT" },
  { code: "13111L", description: "MIDRANGE DATABASE SUPPORT" },
  { code: "13111M", description: "FIXED MAINFRAME APPLICATION SOFTWARE SUPPORT" },
  { code: "13111N", description: "EPASS" },
  { code: "13111P", description: "MIDRANGE APPLICATION STORAGE" },
  { code: "13111Q", description: "DESKTOP" },
  { code: "13111R", description: "MIDRANGE APPLICATION HOSTING" },
  { code: "13111S", description: "SERVER HOSTING" },
  { code: "13111T", description: "SAN STORAGE" },
  { code: "13111U", description: "AFTER HOURS MONITORING & CALLOUT" },
  { code: "13111V", description: "WHOLE OF GOVERNMENT LICENCES" },
  { code: "13111W", description: "VIRUS MANAGEMENT CHARGES" },
  { code: "13111X", description: "TIME AND MATERIALS CHARGES" },
  { code: "13111Y", description: "IT PROCUREMENT CHARGES" },
  { code: "13111Z", description: "MISCELLANEOUS IT CHARGES" },
  { code: "13121A", description: "AFTER HOURS MONITORING AND CALLOUT" },
  { code: "13121B", description: "SERVER HOSTING" },
  { code: "13121C", description: "SERVER TAPE MANAGEMENT" },
  { code: "13121D", description: "DCO MISC CHARGES" },
  { code: "13121E", description: "SERVER HOSTING -GDC" },
  { code: "13121F", description: "SERVER HOSTING - BDC" },
  { code: "13121G", description: "INT DCS HR T&M SERVICES" },
  { code: "13121H", description: "INT LOTUS NOTES LICENCES" },
  { code: "13121I", description: "INT DCS T&M SERVICES" },
  { code: "13121K", description: "INT MIDRANGE OS SUPPORT" },
  { code: "13121L", description: "INT MIDRANGE DATABASE SUPPORT" },
  { code: "13121M", description: "INT FIXED MF APP SOFTWARE SUPPORT" },
  { code: "13121N", description: "INT EPASS" },
  { code: "13121P", description: "INT MIDRANGE APPLICATION STORAGE" },
  { code: "13121R", description: "INT MIDRANGE APPLICATION HOSTING" },
  { code: "13121S", description: "INT SERVER HOSTING" },
  { code: "13121T", description: "INT SAN STORAGE" },
  { code: "13121U", description: "INT AFTER HOURS MONITORING & CALLOUT" },
  { code: "13122A", description: "REMOTE BACKUP AND STORAGE" },
  { code: "13122B", description: "WEBSITE HOSTING" },
  { code: "13122C", description: "SHAREPOINT HOSTING" },
  { code: "13122D", description: "VIRTUAL SERVER HOSTING" },
  { code: "13122E", description: "TRIM ENVIRONMENT HOSTING" },
  { code: "13122F", description: "REMOTE ACCESS - RSA TK" },
  { code: "13122G", description: "APP STORAGE VARIABLE" },
];
