export type YearLookupCustomer = {
  customerId: string;
  customerName: string;
};

export const NEXT_YEAR = "2026-27";
export const CURRENT_YEAR = "2025-26";
export const PRIOR_YEAR = "2024-25";

export const YEAR_LOOKUP_CUSTOMERS: YearLookupCustomer[] = [
  { customerId: "10IBS661001", customerName: "Legislative Assembly" },
  { customerId: "11IBS661001", customerName: "Chief Minister" },
  { customerId: "12IBS661001", customerName: "NT Electoral Commission" },
  { customerId: "13IBS661001", customerName: "OCPE" },
  { customerId: "14IBS661001", customerName: "Auditor General" },
  { customerId: "15IBS661001", customerName: "Ombudsman" },
  { customerId: "16IBS661001", customerName: "PFES" },
  { customerId: "17IBS661001", customerName: "Independent Commissioner Against Corruption " },
  { customerId: "21IBS661001", customerName: "Treasury\\Treasury, Corporation" },
  { customerId: "23IBS661001", customerName: "Land Dev. Corp." },
  { customerId: "27IBS661001", customerName: "Darwin Waterfront Corporation" },
  { customerId: "32IBS661001", customerName: "Aboriginal Areas PA" },
  { customerId: "35IBS661001", customerName: "DOE\\DOE - Corporate Communication" },
  { customerId: "40IBS661001", customerName: "Batchelor Institute of Indigenous Tertiary Education" },
  { customerId: "50IBS661001", customerName: "DEPW" },
  { customerId: "51IBS661003", customerName: "Department of Territory Families, Housing and Communities" },
  { customerId: "60IBS661002", customerName: "DIPL\\DIPL * Redflex" },
  { customerId: "62IBS661001", customerName: "DCDD\\DCDD * NT Fleet" },
  { customerId: "68IBS661001", customerName: "DCDD\\DCDD * CCSRP" },
  { customerId: "68IBS661002", customerName: "DCDD\\DCDD * Application Development" },
  { customerId: "68IBS661003", customerName: "DCDD\\DCDD * AGS - ePASS" },
  { customerId: "68IBS661004", customerName: "DCDD\\DCDD * AGS - ATLASSIAN" },
  { customerId: "68IBS661006", customerName: "DCDD\\DCDD * AGS - NTG Record Systems" },
  { customerId: "68IBS661007", customerName: "DCDD\\DCDD * AGS - GAS Support" },
  { customerId: "68IBS661010", customerName: "DCDD\\DCDD * AGS - ASNEX" },
  { customerId: "68IBS661012", customerName: "DCDD\\DCDD * AGS - EIMS" },
  { customerId: "68IBS661013", customerName: "DCDD\\DCDD * Executive Support" },
  { customerId: "68IBS661014", customerName: "DCDD\\DCDD * AGS - ECMS" },
  { customerId: "68IBS661017", customerName: "DCDD\\DCDD * DCD ICT Services" },
  { customerId: "68IBS661020", customerName: "DCDD\\DCDD * AGS - Progen" },
  { customerId: "68IBS661021", customerName: "DCDD\\DCDD - Data Services - DW - Corporate" },
  { customerId: "68IBS661022", customerName: "DCDD\\DCDD * AGS - TRIPS" },
  { customerId: "68IBS661023", customerName: "DCDD\\DCDD * Training & Employment" },
  { customerId: "68IBS661024", customerName: "DCDD\\DCDD * DCD Taxation Services" },
  { customerId: "68IBS661026", customerName: "DCDD\\DCDD * AGS - FEENIX" },
  { customerId: "68IBS661027", customerName: "DCDD\\DCDD * DCD Enterprise Project Services" },
  { customerId: "68IBS661030", customerName: "DCDD\\DCDD * AGS - Small Systems" },
  { customerId: "68IBS661031", customerName: "DCDD\\DCDD * DCD Digital Communications" },
  { customerId: "68IBS661034", customerName: "DCDD\\DCDD * AGS - GRANTSNT" },
  { customerId: "68IBS661036", customerName: "DCDD\\DCDD * AGS - Procurement Systems" },
  { customerId: "68IBS661037", customerName: "DCDD\\DCDD * EPS - CMSA" },
  { customerId: "68IBS661039", customerName: "DCDD\\DCDD * AGS - HR Systems PAPMS" },
  { customerId: "68IBS661040", customerName: "DCDD\\DCDD * AGS - HR Systems PIPS" },
  { customerId: "68IBS661041", customerName: "DCDD\\DCDD * AGS - HR Systems" },
  { customerId: "68IBS661043", customerName: "DCDD\\DCDD - DENR - ECS ICTS" },
  { customerId: "68IBS661044", customerName: "DCDD\\DCDD - DOE - ECS DIGITAL" },
  { customerId: "68IBS661045", customerName: "DCDD\\DCDD - DIPL - ITM" },
  { customerId: "68IBS661046", customerName: "DCDD\\DCDD - DoH Portfolio Services" },
  { customerId: "68IBS661048", customerName: "DCDD\\DCDD - DoH Telehealth" },
  { customerId: "68IBS661049", customerName: "DCDD\\DCDD - Data Services - DW - Health" },
  { customerId: "68IBS661050", customerName: "DCDD\\DCDD - DHCD - ITM" },
  { customerId: "68IBS661051", customerName: "DCDD\\DCDD - DTSC - ECS DIGITAL BUSINESS SYSTEMS" },
  { customerId: "68IBS661053", customerName: "DCDD\\DCDD - DTSC - ECS WEB" },
  { customerId: "68IBS661054", customerName: "DCDD\\DCDD - DTSC - ECS DIGITAL" },
  { customerId: "68IBS661055", customerName: "DCDD\\DCDD - DPIR - ITM" },
  { customerId: "68IBS661056", customerName: "DCDD\\DCDD - AGD - ITM" },
  { customerId: "68IBS661060", customerName: "DCDD\\DCDD - Treasury - Systems Services" },
  { customerId: "68IBS661062", customerName: "DCDD\\DCDD - TF - IT Management" },
  { customerId: "68IBS661063", customerName: "DCDD\\DCDD - DTBI - Business Systems and Information Services" },
  { customerId: "68IBS661065", customerName: "DCDD\\DCDD * DCD Data Strategy" },
  { customerId: "68IBS661067", customerName: "DCDD\\DCDD - NTPFES - ECS DIGITAL" },
  { customerId: "68IBS661069", customerName: "DCDD\\DCDD * DCD Digital Strategy" },
  { customerId: "68IBS661077", customerName: "DCDD\\DCDD * EPS - NDIS" },
  { customerId: "68IBS661079", customerName: "DCDD\\DCDD * EPS - SAGE" },
  { customerId: "68IBS661080", customerName: "DCDD\\DCDD * EPS - RED TAPE" },
  { customerId: "68IBS661081", customerName: "DCDD\\DCDD * AGS - ELEARNING" },
  { customerId: "68IBS661082", customerName: "DCDD\\DCDD * EPS - COVID-19 DOMESTIC" },
  { customerId: "68IBS661083", customerName: "DCDD\\DCDD * EPS - LDP" },
  { customerId: "68IBS661085", customerName: "DCDD\\DCDD - DATA SERVICES - ONENTG BI" },
  { customerId: "68IBS661087", customerName: "DCDD\\DCDD * EPS - TRO" },
  { customerId: "68IBS661088", customerName: "DCDD\\DCDD - DATA SERVICES - OneNTG ERI" },
  { customerId: "68IBS661089", customerName: "DCDD\\ABS1 BASFM + VEEAM" },
  { customerId: "68IBS661090", customerName: "DCDD\\DCDD - Data Services- WoG Workforce Reporting" },
  { customerId: "68IBS661091", customerName: "DCDD\\DCDD - Workforce Development" },
  { customerId: "68IBS661092", customerName: "DCDD\\DCDD - EPS - Tracer Project" },
  { customerId: "68IBS661093", customerName: "DCDD\\DCDD - Digital Solutions" },
  { customerId: "68IBS661094", customerName: "DCDD\\DCDD * CMSA MDM" },
  { customerId: "68IBS661095", customerName: "DCDD\\DCDD - DATA SERVICES - TFHC DATA WAREHOUSE" },
  { customerId: "68IBS661096", customerName: "DCDD\\DCDD * DENODO" },
  { customerId: "68IBS661098", customerName: "DCDD\\DCDD - Data Services \u2013 Power BI" },
  { customerId: "70IBS661001", customerName: "DOH" },
  { customerId: "79IBS661001", customerName: "AGD\\AGD * Correctional Services" },
  { customerId: "79IBS661003", customerName: "AGD\\AGD * Darwin Correctional Facility Overheads" },
  { customerId: "84IBS661002", customerName: "Territory Wildlife Park" },
  { customerId: "91IBS661002", customerName: "Museum and Art Gallery NT" },
  { customerId: "92IBS661002", customerName: "DITT\\DITT * INDUSTRY, TOURISM AND TRADE" },
  { customerId: "92IBS661003", customerName: "DITT\\DITT * BUSINESS & WORKFORCE" },
  { customerId: "92IBS661004", customerName: "DITT\\DITT * Corporate Communications" },
  { customerId: "92IBS661005", customerName: "DITT\\DITT * MIGRATION NT" },
  { customerId: "92IBS661006", customerName: "DITT\\DITT * TERRITORY BUSINESS CENTRE" },
  { customerId: "DCISDBS500", customerName: "DCDD\\DCDD * DCS Enterprise Storage" },
  { customerId: "DCISDBS501", customerName: "DCDD\\DCDD * DCS Data Centre Operations" },
  { customerId: "DCISDBS504", customerName: "DCDD\\DCDD * DCS Midrange Services" },
  { customerId: "DCISMBS504", customerName: "DCDD\\DCDD * DCS Mainframe Services" },
  { customerId: "DCISWBS500", customerName: "DCDD\\DCDD * DCS Whole of Government" },
  { customerId: "XXIBS661003", customerName: "Telstra, Darwin" },
  { customerId: "XXIBS661004", customerName: "NT BUILD" },
  { customerId: "XXIBS661006", customerName: "CouncilBiz" },
  { customerId: "XXIBS661007", customerName: "Territory Generation" },
  { customerId: "XXIBS661008", customerName: "PWC" },
  { customerId: "XXIBS661016", customerName: "Jacana Energy" },
  { customerId: "XXIBS661019", customerName: "AARNET" },
];
